// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Customers {
  constructor(public client: WrapperClient) {}
  /**
   * Crear cliente
   *
   * Registra un nuevo cliente en Facturapi.
   *
   * Esta llamada valida que los datos fiscales coincidan con
   * los registros del SAT para ese RFC, de lo contrario, la llamada
   * devolverá un error indicando el problema.
   *
   * Una vez creado el cliente y obtenido un objeto de respuesta,
   * te recomendamos guardar el ID en tu base de datos junto a la información
   * de tu cliente. Posteriormente, puedes llamar al endpoint de Crear Factura
   * pasando el ID del cliente en lugar de repetir la información.
   *
   * Por último, ten en cuenta que los clientes que crees en ambiente _Test_ **no se
   * comparten** con el ambiente _Live_.
   *
   */
  create(
    data: OperationBody<'createCustomer'>,
    params?: OperationQuery<'createCustomer'> | null,
  ): Promise<OperationResponse<'createCustomer'>> {
    return this.client.request<OperationResponse<'createCustomer'>>(
      `/customers`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createCustomer,
        body: data,
        params: params,
      },
    )
  }

  /**
   * Listar clientes
   *
   * Regresa una lista paginada de todos los clientes de una organización o realiza una búsqueda de acuerdo a parámetros
   */
  list(
    params?: OperationQuery<'listCustomers'> | null,
  ): Promise<OperationResponse<'listCustomers'>> {
    return this.client.request<OperationResponse<'listCustomers'>>(
      `/customers`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listCustomers,
        params: params,
      },
    )
  }

  /**
   * Obtener cliente por ID
   *
   * Regresa el objeto 'Customer' relacionado al `id` especificado.
   */
  retrieve(id: string): Promise<OperationResponse<'getCustomer'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getCustomer'>>(
      `/customers/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getCustomer },
    )
  }

  /**
   * Editar cliente
   *
   * Actualiza la información de un cliente existente, asignando los valores de los parámetros enviados. Los parámetros que no se envíen en la petición no se modificarán.
   */
  update(
    id: string,
    data: OperationBody<'editCustomer'>,
    params?: OperationQuery<'editCustomer'> | null,
  ): Promise<OperationResponse<'editCustomer'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'editCustomer'>>(
      `/customers/${encodeURIComponent(id)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.editCustomer,
        body: data,
        params: params,
      },
    )
  }

  /**
   * Eliminar cliente
   *
   * Elimina el cliente de tu organización. Las facturas asociadas al cliente **no** se eliminarán.
   */
  del(id: string): Promise<OperationResponse<'deleteCustomer'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'deleteCustomer'>>(
      `/customers/${encodeURIComponent(id)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteCustomer },
    )
  }

  /**
   * Validar información fiscal
   *
   * Valida que la información fiscal del cliente coincida con los registros del SAT.
   *
   * Su función principal es validar que los datos del cliente registrado siguen cumpliendo la validación del SAT.
   *
   * :::tip
   *   Las operaciones de crear cliente, editar cliente y crear factura ya realizan una
   *   validación de la información del cliente, por lo que **no** es necesario llamar a este endpoint
   *   antes de realizar dichas operaciones.
   * :::
   *
   */
  validateTaxInfo(
    id: string,
  ): Promise<OperationResponse<'validateCustomerTaxInfo'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'validateCustomerTaxInfo'>>(
      `/customers/${encodeURIComponent(id)}/tax-info-validation`,
      { method: 'GET', datePlan: operationDatePlans.validateCustomerTaxInfo },
    )
  }

  /**
   * Enviar enlace de edición por correo electrónico
   *
   * Envía un enlace para que el cliente pueda editar su información fiscal.
   *
   * Este enlace estará disponible en el campo `edit_link`, será válido por 7 días y sólo se podrá usar una vez.
   *
   */
  sendEditLinkByEmail(
    id: string,
    options: OperationBody<'sendEditLinkByEmail'>,
  ): Promise<OperationResponse<'sendEditLinkByEmail'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'sendEditLinkByEmail'>>(
      `/customers/${encodeURIComponent(id)}/email-edit-link`,
      {
        method: 'POST',
        datePlan: operationDatePlans.sendEditLinkByEmail,
        body: options,
      },
    )
  }
}
