// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Invoices {
  constructor(public client: WrapperClient) {}
  /**
   * Crear factura (CFDI 4.0)
   *
   * Crea una nueva Factura. Si la factura es creada en ambiente Live, ésta será **timbrada y enviada al SAT**.
   *
   * Revisa e infórmate sobre el [rescate de CFDI en intermitencias (Status 202)](https://docs.facturapi.io/docs/guides/invoices/intermitencias).
   *
   * @param body - Datos de la solicitud.
   * @param params - Parámetros de consulta.
   * @returns 200: Nuevo objeto `Invoice` creado
   * 202: Solicitud aceptada; Facturapi intentará recuperar el CFDI hasta cinco veces, una cada 10 minutos
   */
  create(
    body: OperationBody<'createInvoice'>,
    params?: OperationQuery<'createInvoice'> | null,
  ): Promise<OperationResponse<'createInvoice'>> {
    return this.client.request<OperationResponse<'createInvoice'>>(
      `/invoices`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createInvoice,
        body: body,
        params: params,
      },
    )
  }

  /**
   * Listar facturas
   *
   * Regresa una lista paginada de todas las facturas de una organización o realiza una búsqueda de acuerdo a parámetros.
   *
   * Por defecto, los resultados se ordenan por fecha de emisión, usando el campo `date` de forma descendente.
   *
   * @param params - Parámetros de consulta.
   * @returns Resultado de la búsqueda
   */
  list(
    params?: OperationQuery<'listInvoices'> | null,
  ): Promise<OperationResponse<'listInvoices'>> {
    return this.client.request<OperationResponse<'listInvoices'>>(`/invoices`, {
      method: 'GET',
      datePlan: operationDatePlans.listInvoices,
      params: params,
    })
  }

  /**
   * Obtener factura por ID
   *
   * Regresa el objeto 'Invoice' relacionado al `id` especificado.
   *
   * @param id - ID del objeto a obtener
   * @returns Objeto `Invoice`
   */
  retrieve(id: string): Promise<OperationResponse<'getInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getInvoice'>>(
      `/invoices/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getInvoice },
    )
  }

  /**
   * Resumen de pago
   *
   * Devuelve la información necesaria para agregar esta factura como documento relacionado en un
   * Comprobante de Pago (complemento de pago): el número de parcialidad que corresponde según el
   * historial de pagos, el saldo anterior (`last_balance`) y el desglose de impuestos de la factura
   * prorrateado al monto que se pretende pagar.
   *
   * El valor de retorno está listo para usarse como elemento de `related_documents` al
   * [crear una factura de tipo Pago](https://docs.facturapi.io/api/#tag/invoice/operation/createInvoice).
   *
   * El parámetro `amount` debe expresarse en la divisa de la factura y no puede exceder el saldo
   * pendiente (`amount_due`). Cuando el pago se recibe en otra divisa, convierte el monto antes de
   * llamar este método.
   *
   * @param id - ID de la factura de ingreso (método de pago PPD) que se desea pagar
   * @param params - Parámetros de consulta.
   * @param params.amount - Monto que se paga de esta factura, expresado en la divisa de la factura. No puede exceder el saldo pendiente.
   * @returns Resumen del documento relacionado
   */
  paymentSummary(
    id: string,
    params: OperationQuery<'getInvoicePaymentSummary'>,
  ): Promise<OperationResponse<'getInvoicePaymentSummary'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getInvoicePaymentSummary'>>(
      `/invoices/${encodeURIComponent(id)}/payment-summary`,
      {
        method: 'GET',
        datePlan: operationDatePlans.getInvoicePaymentSummary,
        params: params,
      },
    )
  }

  /**
   * Cancelar factura
   *
   * Realiza una solicitud de cancelación de factura ante el SAT, soportando el esquema de cancelación 2022.
   *
   * Al usar este método pueden ocurrir 3 posibles resultados:
   *
   * - Que la llamada regrese un error con la explicación de por qué no se pudo cancelar.
   * - Que la llamada sea satisfactoria y regrese un objeto `invoice` con la propiedad `status: "canceled"`.
   * - Que la llamada sea satisfactoria, pero que la cancelación requiera de confirmación de parte de tu cliente, en cuyo caso se obtendrá como respuesta el objeto `invoice` con las propiedades `status: "valid"` y `cancellation_status: "pending"`.
   *
   * En el tercer escenario, el valor de `cancellation_status` será actualizado automáticamente por Facturapi cuando tu cliente acepte, rechace o deje expirar la solicitud, de tal manera que al consultar una factura (usando [Obtener Factura](https://docs.facturapi.io/api/#tag/invoice/operation/getInvoice)), la propiedad `cancellation_status` reflejará el estado más reciente de la solicitud.
   *
   * Consulta los valores posibles de `cancellation_status` más abajo.
   *
   * Después de la cancelación la factura ya no tendrá validez, el objeto cambiará su `status` a `"canceled"` y seguirá estando disponible para futuras consultas.
   *
   * Si el status de la factura es `draft`, este método la eliminará de la base de datos.
   *
   * Si el status de la factura es `canceled`, este método regresará un error.
   *
   * @param id - ID de la factura a cancelar
   * @param params - Parámetros de consulta.
   * @param params.motive - Clave que representa el motivo de la cancelación de la factura.
   *
   * - `01`: **Comprobante emitido con errores con relación**. Cuando la
   *   factura contiene algún error en las cantidades, claves o cualquier otro dato y ya
   *   se ha emitido el comprobante que la sustituye, el cual deberá indicarse por medio
   *   del atributo `substitution`.
   * - `02`: **Comprobante emitido con errores sin relación**. Cuando la
   *   factura contiene algún error en las cantidades, claves o cualquier otro dato y no
   *   se requiere relacionar con otra factura.
   * - `03`: **No se llevó a cabo la operación**. Cuando la venta o transacción no se concretó.
   * - `04`: **Operación nominativa relacionada en la factura global**. Cuando se requiere cancelar
   *   una factura al público en general porque el cliente solicita su comprobante.
   *
   * @returns Solicitud de cancelación exitosa
   */
  cancel(
    id: string,
    params: OperationQuery<'cancelInvoice'>,
  ): Promise<OperationResponse<'cancelInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'cancelInvoice'>>(
      `/invoices/${encodeURIComponent(id)}`,
      {
        method: 'DELETE',
        datePlan: operationDatePlans.cancelInvoice,
        params: params,
      },
    )
  }

  /**
   * Enviar factura por correo electrónico
   *
   * Envía un correo electrónico a la dirección de tu cliente, con los archivos XML y PDF adjuntos al mensaje.
   *
   * @param id - ID del objeto a obtener
   * @param options - Datos de la solicitud.
   * @returns Objeto genérico de respuesta
   */
  sendByEmail(
    id: string,
    options?: OperationBody<'sendInvoiceByEmail'>,
  ): Promise<OperationResponse<'sendInvoiceByEmail'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'sendInvoiceByEmail'>>(
      `/invoices/${encodeURIComponent(id)}/email`,
      {
        method: 'POST',
        datePlan: operationDatePlans.sendInvoiceByEmail,
        body: options,
      },
    )
  }

  /**
   * Descargar factura
   *
   * Descarga tu Factura en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadPdf(id: string): Promise<OperationResponse<'downloadInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadInvoice'>>(
      `/invoices/${encodeURIComponent(id)}/pdf`,
      { method: 'GET', datePlan: operationDatePlans.downloadInvoice },
    )
  }

  /**
   * Descargar factura
   *
   * Descarga tu Factura en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadXml(id: string): Promise<OperationResponse<'downloadInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadInvoice'>>(
      `/invoices/${encodeURIComponent(id)}/xml`,
      { method: 'GET', datePlan: operationDatePlans.downloadInvoice },
    )
  }

  /**
   * Descargar factura
   *
   * Descarga tu Factura en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadZip(id: string): Promise<OperationResponse<'downloadInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadInvoice'>>(
      `/invoices/${encodeURIComponent(id)}/zip`,
      { method: 'GET', datePlan: operationDatePlans.downloadInvoice },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la factura en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadPdfUrl(
    id: string,
  ): Promise<OperationResponse<'getInvoiceDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getInvoiceDownloadUrl'>>(
      `/invoices/${encodeURIComponent(id)}/download-url/pdf`,
      { method: 'GET', datePlan: operationDatePlans.getInvoiceDownloadUrl },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la factura en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadXmlUrl(
    id: string,
  ): Promise<OperationResponse<'getInvoiceDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getInvoiceDownloadUrl'>>(
      `/invoices/${encodeURIComponent(id)}/download-url/xml`,
      { method: 'GET', datePlan: operationDatePlans.getInvoiceDownloadUrl },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la factura en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadZipUrl(
    id: string,
  ): Promise<OperationResponse<'getInvoiceDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getInvoiceDownloadUrl'>>(
      `/invoices/${encodeURIComponent(id)}/download-url/zip`,
      { method: 'GET', datePlan: operationDatePlans.getInvoiceDownloadUrl },
    )
  }

  /**
   * Crear o recuperar solicitud de ZIP mensual
   *
   * Crea una solicitud para generar un archivo ZIP con las facturas de un mes, o recupera la solicitud existente con los mismos filtros.
   *
   * La operación es idempotente. Los tipos de factura se normalizan, por lo que `["I", "E"]` y `["E", "I"]` corresponden a la misma solicitud. Las llamadas concurrentes idénticas también regresan la misma solicitud.
   *
   * Si una solicitud anterior tiene status `failed`, volver a llamar este método reintentará su procesamiento. Antes del nuevo intento se limpian el error, la tarea anterior, el progreso procesado y la lista de documentos fallidos. Si no es posible programar la generación, la solicitud se guarda con status `failed` y la API regresa un error `5xx`.
   *
   * Este método requiere una llave de API de organización en ambiente Live, una suscripción activa y permiso para leer facturas. Las llaves de ambiente Test regresan HTTP 402.
   *
   * @param data - Datos de la solicitud.
   * @returns Solicitud de ZIP creada o recuperada correctamente.
   */
  createZipRequest(
    data: OperationBody<'createInvoiceZipRequest'>,
  ): Promise<OperationResponse<'createInvoiceZipRequest'>> {
    return this.client.request<OperationResponse<'createInvoiceZipRequest'>>(
      `/invoices/zip-requests`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createInvoiceZipRequest,
        body: data,
      },
    )
  }

  /**
   * Listar solicitudes de ZIP mensual
   *
   * Regresa una lista paginada de solicitudes de ZIP. `year` y `month` deben enviarse juntos. `invoice_types` filtra por un tipo o por un arreglo normalizado exacto.
   *
   * Este método requiere una llave de API de organización en ambiente Live, una suscripción activa y permiso para leer facturas.
   *
   * @param params - Parámetros de consulta.
   * @returns Resultado paginado de solicitudes de ZIP.
   */
  listZipRequests(
    params?: OperationQuery<'listInvoiceZipRequests'> | null,
  ): Promise<OperationResponse<'listInvoiceZipRequests'>> {
    return this.client.request<OperationResponse<'listInvoiceZipRequests'>>(
      `/invoices/zip-requests`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listInvoiceZipRequests,
        params: params,
      },
    )
  }

  /**
   * Recuperar solicitud de ZIP mensual
   *
   * Recupera una solicitud de ZIP. Consulta este método hasta que el status sea `finished` o `failed`. Cuando sea `finished`, descarga el archivo con el método de descarga.
   *
   * Requiere una llave de API de organización en ambiente Live, una suscripción activa y permiso para leer facturas.
   *
   * @param id - Identificador de la solicitud de ZIP.
   * @returns Solicitud de ZIP recuperada correctamente.
   */
  retrieveZipRequest(
    id: string,
  ): Promise<OperationResponse<'retrieveInvoiceZipRequest'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'retrieveInvoiceZipRequest'>>(
      `/invoices/zip-requests/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.retrieveInvoiceZipRequest },
    )
  }

  /**
   * Descargar ZIP mensual
   *
   * Descarga el ZIP de una solicitud terminada. El nombre del archivo usa el formato `YYYY-MM.zip`.
   *
   * Requiere una llave de API de organización en ambiente Live, una suscripción activa y permiso para leer facturas.
   *
   * @param id - Identificador de la solicitud de ZIP.
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadZipRequest(
    id: string,
  ): Promise<OperationResponse<'downloadInvoiceZipRequest'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadInvoiceZipRequest'>>(
      `/invoices/zip-requests/${encodeURIComponent(id)}/zip`,
      { method: 'GET', datePlan: operationDatePlans.downloadInvoiceZipRequest },
    )
  }

  /**
   * Obtener URL de descarga del ZIP mensual
   *
   * Devuelve una URL temporal para descargar el ZIP de una solicitud terminada sin que el archivo viaje a través de tu servidor.
   *
   * La URL permite acceder únicamente a ese archivo mientras sea válida: trátala como una credencial y no la almacenes. Requiere una llave de API de organización en ambiente Live, una suscripción activa y permiso para leer facturas.
   *
   * @param id - Identificador de la solicitud de ZIP.
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadZipRequestUrl(
    id: string,
  ): Promise<OperationResponse<'getInvoiceZipRequestDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'getInvoiceZipRequestDownloadUrl'>
    >(`/invoices/zip-requests/${encodeURIComponent(id)}/download-url`, {
      method: 'GET',
      datePlan: operationDatePlans.getInvoiceZipRequestDownloadUrl,
    })
  }

  /**
   * Descargar acuse de cancelación
   *
   * Descarga en XML o PDF el acuse emitido por el SAT al solicitar la cancelación mediante Facturapi. El acuse contiene el resultado inmediato de la solicitud y no necesariamente acredita que el CFDI ya esté cancelado; consulta el estado de la factura para confirmar el desenlace.
   *
   * @param id - ID del objeto a obtener
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadCancellationReceiptXml(
    id: string,
  ): Promise<OperationResponse<'downloadCancellationReceiptXml'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'downloadCancellationReceiptXml'>
    >(`/invoices/${encodeURIComponent(id)}/cancellation_receipt/xml`, {
      method: 'GET',
      datePlan: operationDatePlans.downloadCancellationReceiptXml,
    })
  }

  /**
   * Descargar acuse de cancelación
   *
   * Descarga en XML o PDF el acuse emitido por el SAT al solicitar la cancelación mediante Facturapi. El acuse contiene el resultado inmediato de la solicitud y no necesariamente acredita que el CFDI ya esté cancelado; consulta el estado de la factura para confirmar el desenlace.
   *
   * @param id - ID del objeto a obtener
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadCancellationReceiptPdf(
    id: string,
  ): Promise<OperationResponse<'downloadCancellationReceiptXml'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'downloadCancellationReceiptXml'>
    >(`/invoices/${encodeURIComponent(id)}/cancellation_receipt/pdf`, {
      method: 'GET',
      datePlan: operationDatePlans.downloadCancellationReceiptXml,
    })
  }

  /**
   * Obtener enlace del acuse de cancelación
   *
   * Devuelve un enlace temporal para descargar en XML o PDF el acuse emitido por el SAT al solicitar la cancelación mediante Facturapi. El acuse contiene el resultado inmediato de la solicitud y no necesariamente acredita que el CFDI ya esté cancelado; consulta el estado de la factura para confirmar el desenlace.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadCancellationReceiptPdfUrl(
    id: string,
  ): Promise<OperationResponse<'getCancellationReceiptDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'getCancellationReceiptDownloadUrl'>
    >(
      `/invoices/${encodeURIComponent(id)}/cancellation_receipt/download-url/pdf`,
      {
        method: 'GET',
        datePlan: operationDatePlans.getCancellationReceiptDownloadUrl,
      },
    )
  }

  /**
   * Obtener enlace del acuse de cancelación
   *
   * Devuelve un enlace temporal para descargar en XML o PDF el acuse emitido por el SAT al solicitar la cancelación mediante Facturapi. El acuse contiene el resultado inmediato de la solicitud y no necesariamente acredita que el CFDI ya esté cancelado; consulta el estado de la factura para confirmar el desenlace.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadCancellationReceiptXmlUrl(
    id: string,
  ): Promise<OperationResponse<'getCancellationReceiptDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'getCancellationReceiptDownloadUrl'>
    >(
      `/invoices/${encodeURIComponent(id)}/cancellation_receipt/download-url/xml`,
      {
        method: 'GET',
        datePlan: operationDatePlans.getCancellationReceiptDownloadUrl,
      },
    )
  }

  /**
   * Editar borrador de factura
   *
   * Actualiza la información de una factura con status `draft`, asignando
   * los valores de los parámetros enviados. Los parámetros que no se envíen
   * en la petición no se modificarán.
   *
   * En el objeto `invoice` de respuesta, Facturapi asignará automáticamente
   * el campo `is_ready_to_stamp` con el valor `true` si la factura pasa la
   * validación mínima requerida para ser timbrada; de lo contrario, el campo
   * `is_ready_to_stamp` será `false`.
   *
   * @param id - ID del objeto a editar
   * @param data - Datos de la solicitud.
   * @returns Objeto `Invoice` editado correctamente
   */
  updateDraft(
    id: string,
    data: OperationBody<'updateDraftInvoice'>,
  ): Promise<OperationResponse<'updateDraftInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'updateDraftInvoice'>>(
      `/invoices/${encodeURIComponent(id)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateDraftInvoice,
        body: data,
      },
    )
  }

  /**
   * Timbrar borrador de factura
   *
   * Timbra una factura con status `draft` y la envía al SAT para su validación.
   *
   * Al usar este método, el valor del campo `is_ready_to_stamp` (asignado por Facturapi)
   * deberá ser `true`. De otra forma, la llamada regresará un error.
   *
   * Este método no permite editar la factura, sólo timbrarla. Si necesitas editar información
   * en la factura antes de timbrarla, usa el método [Editar Borrador de Factura](https://docs.facturapi.io/api/#tag/invoice/operation/editDraftInvoice).
   *
   * @param id - ID del objeto a timbrar
   * @param params - Parámetros de consulta.
   * @returns Objeto `Invoice` timbrado correctamente
   */
  stampDraft(
    id: string,
    params?: OperationQuery<'stampDraftInvoice'> | null,
  ): Promise<OperationResponse<'stampDraftInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'stampDraftInvoice'>>(
      `/invoices/${encodeURIComponent(id)}/stamp`,
      {
        method: 'POST',
        datePlan: operationDatePlans.stampDraftInvoice,
        params: params,
      },
    )
  }

  /**
   * Actualizar status de factura
   *
   * Consulta el status de una factura timbrada en el SAT y actualiza el objeto invoice
   * con La información más reciente.
   *
   * @param id - ID del objeto invoice a actualizar
   * @returns Objeto `Invoice` actualizado
   */
  updateStatus(id: string): Promise<OperationResponse<'updateInvoiceStatus'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'updateInvoiceStatus'>>(
      `/invoices/${encodeURIComponent(id)}/status`,
      { method: 'PUT', datePlan: operationDatePlans.updateInvoiceStatus },
    )
  }

  /**
   * Copiar a borrador
   *
   * Crea una copia en borrador de la factura especificada.
   *
   * @param id - ID de la factura a copiar
   * @returns Nuevo objeto `Invoice` con status `draft`.
   */
  copyToDraft(id: string): Promise<OperationResponse<'copyToDraftInvoice'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'copyToDraftInvoice'>>(
      `/invoices/${encodeURIComponent(id)}/copy`,
      { method: 'POST', datePlan: operationDatePlans.copyToDraftInvoice },
    )
  }

  /**
   * Vista previa de factura en PDF
   *
   * Genera una vista previa en PDF de una factura sin timbrar ni guardar en la organización.
   *
   * @param body - Datos de la solicitud.
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  previewPdf(
    body: OperationBody<'previewInvoicePdf'>,
  ): Promise<OperationResponse<'previewInvoicePdf'>> {
    return this.client.request<OperationResponse<'previewInvoicePdf'>>(
      `/invoices/preview/pdf`,
      {
        method: 'POST',
        datePlan: operationDatePlans.previewInvoicePdf,
        body: body,
      },
    )
  }

  /**
   * Obtener URL del preview PDF de factura
   *
   * Devuelve una URL temporal para el preview PDF de una factura sin timbrar.
   *
   * @param body - Datos de la solicitud.
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  previewPdfUrl(
    body: OperationBody<'previewInvoicePdfUrl'>,
  ): Promise<OperationResponse<'previewInvoicePdfUrl'>> {
    return this.client.request<OperationResponse<'previewInvoicePdfUrl'>>(
      `/invoices/preview/pdf/download-url`,
      {
        method: 'POST',
        datePlan: operationDatePlans.previewInvoicePdfUrl,
        body: body,
      },
    )
  }
}
