// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
import type { BinaryInput } from '../types/runtime'
import { prepareFile } from '../runtime/uploads'
export default class Organizations {
  constructor(public client: WrapperClient) {}
  /**
   * Crear organización
   *
   * Crea una nueva Organización que pertenecerá a tu cuenta de usuario.
   *
   * Después de crear la organización y antes de poder emitir facturas con
   * la organización, deberás de terminar de configurarla llamando a los
   * métodos de [Actualizar datos fiscales](#tag/organization/operation/editOrganizationLegal) y
   * [Subir certificados (CSD)](#tag/organization/operation/uploadOrganizationCertificate)
   *
   *
   * Después de crear la organización y antes de poder emitir facturas con
   * la organización, deberás de terminar de configurarla llamando a los
   * métodos de [Actualizar datos fiscales](#tag/organization/operation/editOrganizationLegal) y
   * [Subir certificados (CSD)](#tag/organization/operation/uploadOrganizationCertificate),
   * además de firmar la Carta Manifiesto que autoriza a nuestro PAC a timbrar facturas;
   * puedes hacerlo en [tu dashboard](https://dashboard.facturapi.io/settings/manifiesto)
   * o en [nuestro portal público](https://www.facturapi.io/manifiesto). También puedes incrustar
   * en tu solución el módulo de firma de la carta (sin logos, listo para iframe): https://www.facturapi.io/embedded/manifiesto
   *
   * Recuerda que los folios de tu suscripción podrán ser consumidos por
   * cualquiera de las organizaciones registradas bajo tu cuenta.
   *
   */
  create(
    data: OperationBody<'createOrganization'>,
  ): Promise<OperationResponse<'createOrganization'>> {
    return this.client.request<OperationResponse<'createOrganization'>>(
      `/organizations`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createOrganization,
        body: data,
      },
    )
  }

  /**
   * Listar organizaciones
   *
   * Regresa una lista paginada de todas las organizationes registradas bajo tu cuenta, o realiza una búsqueda de acuerdo a parámetros.
   */
  list(
    params?: OperationQuery<'listOrganizations'> | null,
  ): Promise<OperationResponse<'listOrganizations'>> {
    return this.client.request<OperationResponse<'listOrganizations'>>(
      `/organizations`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listOrganizations,
        params: params,
      },
    )
  }

  /**
   * Obtener organización por ID
   *
   * Regresa el objeto 'Organization' relacionado al `id` especificado.
   */
  retrieve(id: string): Promise<OperationResponse<'getOrganization'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getOrganization'>>(
      `/organizations/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getOrganization },
    )
  }

  /**
   * Editar datos fiscales
   *
   * Actualiza los datos fiscales de la organización.
   *
   * Si estás buscando cómo editar el RFC, recuerda que la propiedad
   * `tax_id` se asigna automáticamente al subir los Certificados de Sello
   * Digital.
   *
   */
  updateLegal(
    id: string,
    data: OperationBody<'editOrganizationLegal'>,
  ): Promise<OperationResponse<'editOrganizationLegal'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'editOrganizationLegal'>>(
      `/organizations/${encodeURIComponent(id)}/legal`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.editOrganizationLegal,
        body: data,
      },
    )
  }

  /**
   * Editar personalización
   *
   * Actualiza la información relacionada con la identidad o branding de la organización.
   *
   */
  updateCustomization(
    id: string,
    data: OperationBody<'editOrganizationCustomization'>,
  ): Promise<OperationResponse<'editOrganizationCustomization'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'editOrganizationCustomization'>
    >(`/organizations/${encodeURIComponent(id)}/customization`, {
      method: 'PUT',
      datePlan: operationDatePlans.editOrganizationCustomization,
      body: data,
    })
  }

  /**
   * Editar config. recibos
   *
   * Actualiza los campos enviados de la configuración de recibos de la organización.
   * Para activar la generación automática de facturas globales, la organización
   * debe tener contratado ese feature.
   *
   */
  updateReceiptSettings(
    id: string,
    data: OperationBody<'editOrganizationReceiptsSettings'>,
  ): Promise<OperationResponse<'editOrganizationReceiptsSettings'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'editOrganizationReceiptsSettings'>
    >(`/organizations/${encodeURIComponent(id)}/receipts`, {
      method: 'PUT',
      datePlan: operationDatePlans.editOrganizationReceiptsSettings,
      body: data,
    })
  }

  /**
   * Elegir dominio de autofactura
   *
   * Elige el dominio que utilizará esta organización en su micrositio de
   * autofactura. Una vez elegido el dominio, deberás ponerte en contacto
   * con nosotros si necesitas cambiarlo.
   *
   * El dominio que elijas será el que aparecerá en el campo
   * `self_invoice_url` al crear un nuevo recibo, de la siguiente manera:
   *
   * `https://factura.space/{DOMAIN}/{RECEIPT_KEY}`
   *
   */
  updateDomain(
    id: string,
    data: OperationBody<'editOrganizationDomain'>,
  ): Promise<OperationResponse<'editOrganizationDomain'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'editOrganizationDomain'>>(
      `/organizations/${encodeURIComponent(id)}/domain`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.editOrganizationDomain,
        body: data,
      },
    )
  }

  /**
   * Revisar dominio disponible
   *
   * Revisa si un identificador está disponible para elegir como dominio para el portal de autofactura.
   */
  checkDomainIsAvailable(
    data: OperationQuery<'checkDomainAvailability'>,
  ): Promise<OperationResponse<'checkDomainAvailability'>> {
    return this.client.request<OperationResponse<'checkDomainAvailability'>>(
      `/organizations/domain-check`,
      {
        method: 'GET',
        datePlan: operationDatePlans.checkDomainAvailability,
        params: data,
      },
    )
  }

  /**
   * Subir logotipo
   *
   * Sube el logotipo de la organización que será colocado en el PDF y en
   * los correos que se envían al cliente con la factura adjunta.
   *
   * El archivo debe ser una imagen en formato JPG o PNG y tener un tamaño
   * no mayor a 500 KB. Las dimensiones recomendadas son 800 × 500px.
   *
   * Si la organización ya tiene un logotipo, esta llamada reemplaza el
   * logotipo anterior.
   *
   */
  async uploadLogo(
    id: string,
    file: BinaryInput,
  ): Promise<OperationResponse<'uploadOrganizationLogo'>> {
    if (!id) return Promise.reject(new Error('id is required'))
    if (typeof FormData === 'undefined')
      throw new Error(
        'FormData is not available in this runtime. Use Node.js 18+ or provide a FormData implementation.',
      )
    const formData = new FormData()
    formData.append(
      'file',
      await prepareFile(file, 'application/octet-stream'),
      'file',
    )
    return this.client.request<OperationResponse<'uploadOrganizationLogo'>>(
      `/organizations/${encodeURIComponent(id)}/logo`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.uploadOrganizationLogo,
        formData,
      },
    )
  }

  /**
   * Subir certificados (CSD)
   *
   * Sube los archivos del Certificado de Sello Digital (CSD) proporcionado
   * por el SAT. Esta llamada también debe usarse para reemplazar los
   * certificados existentes en caso de solicitar nuevos.
   *
   * Al actualizar tus certificados se leerá el RFC y asignará
   * automáticamente a `legal.tax_id`.
   *
   */
  async uploadCertificate(
    id: string,
    cerFile: BinaryInput,
    keyFile: BinaryInput,
    password: string,
  ): Promise<OperationResponse<'uploadOrganizationCertificate'>> {
    if (!id) return Promise.reject(new Error('id is required'))
    if (typeof FormData === 'undefined')
      throw new Error(
        'FormData is not available in this runtime. Use Node.js 18+ or provide a FormData implementation.',
      )
    const formData = new FormData()
    const [cer, key] = await Promise.all([
      prepareFile(cerFile, 'application/octet-stream'),
      prepareFile(keyFile, 'application/octet-stream'),
    ])
    formData.append('cer', cer, 'cer.cer')
    formData.append('key', key, 'key.key')
    formData.append('password', password)
    return this.client.request<
      OperationResponse<'uploadOrganizationCertificate'>
    >(`/organizations/${encodeURIComponent(id)}/certificate`, {
      method: 'PUT',
      datePlan: operationDatePlans.uploadOrganizationCertificate,
      formData,
    })
  }

  /**
   * Eliminar certificados (CSD)
   *
   * Elimina los certificados (CSD) de tu organización.
   *
   * Esto no afecta a las facturas ya emitidas, pero no podrás emitir nuevas facturas hasta que subas nuevos certificados.
   *
   */
  deleteCertificate(
    id: string,
  ): Promise<OperationResponse<'deleteOrganizationCertificate'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'deleteOrganizationCertificate'>
    >(`/organizations/${encodeURIComponent(id)}/certificate`, {
      method: 'DELETE',
      datePlan: operationDatePlans.deleteOrganizationCertificate,
    })
  }

  /**
   * Eliminar organización
   *
   * Elimina la organización de tu cuenta de Facturapi. Una vez eliminada,
   * ya no podrás acceder a sus recursos, tales como clientes, productos,
   * facturas, recibos o retenciones.
   *
   */
  del(id: string): Promise<OperationResponse<'deleteOrganization'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'deleteOrganization'>>(
      `/organizations/${encodeURIComponent(id)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteOrganization },
    )
  }

  /**
   * Obtener Test Api Key
   *
   * Obtiene la llave secreta de ambiente Test de la organización.
   */
  getTestApiKey(id: string): Promise<OperationResponse<'getTestApiKey'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getTestApiKey'>>(
      `/organizations/${encodeURIComponent(id)}/apikeys/test`,
      { method: 'GET', datePlan: operationDatePlans.getTestApiKey },
    )
  }

  /**
   * Renovar Test API Key
   *
   * Renueva la llave secreta de ambiente Test de la organización e invalida inmediatamente la anterior.
   *
   */
  renewTestApiKey(id: string): Promise<OperationResponse<'renewTestApiKey'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'renewTestApiKey'>>(
      `/organizations/${encodeURIComponent(id)}/apikeys/test`,
      { method: 'PUT', datePlan: operationDatePlans.renewTestApiKey },
    )
  }

  /**
   * Listar Live API Keys
   *
   * Listar llaves secretas de ambiente Live de la organización.
   *
   */
  listLiveApiKeys(id: string): Promise<OperationResponse<'listLiveApiKeys'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'listLiveApiKeys'>>(
      `/organizations/${encodeURIComponent(id)}/apikeys/live`,
      { method: 'GET', datePlan: operationDatePlans.listLiveApiKeys },
    )
  }

  /**
   * Crear Live API Key
   *
   * Genera una nueva llave secreta de ambiente Live de la organización.
   * Esta operación no invalida las llaves generadas previamente. El endpoint usa `PUT`
   * por compatibilidad histórica, pero su comportamiento es crear una nueva llave.
   *
   */
  renewLiveApiKey(id: string): Promise<OperationResponse<'renewLiveApiKey'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'renewLiveApiKey'>>(
      `/organizations/${encodeURIComponent(id)}/apikeys/live`,
      { method: 'PUT', datePlan: operationDatePlans.renewLiveApiKey },
    )
  }

  /**
   * Revocar Live API Key
   *
   * Revocar Live Api Key de tu organización.
   *
   */
  deleteLiveApiKey(
    organizationId: string,
    apiKeyId: string,
  ): Promise<OperationResponse<'deleteLiveApiKey'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!apiKeyId) return Promise.reject(new Error('apiKeyId is required'))

    return this.client.request<OperationResponse<'deleteLiveApiKey'>>(
      `/organizations/${encodeURIComponent(organizationId)}/apikeys/live/${encodeURIComponent(apiKeyId)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteLiveApiKey },
    )
  }

  /**
   * Listado de series
   *
   * Listado de series creadas para la personalización de organización. La cual lleva control de foliaje para cada tipo de factura si está asignada en las personalización de organización.
   *
   */
  listSeriesGroup(
    organization_id: string,
  ): Promise<OperationResponse<'getSeriesGroup'>> {
    if (!organization_id)
      return Promise.reject(new Error('organization_id is required'))

    return this.client.request<OperationResponse<'getSeriesGroup'>>(
      `/organizations/${encodeURIComponent(organization_id)}/series-group`,
      { method: 'GET', datePlan: operationDatePlans.getSeriesGroup },
    )
  }

  /**
   * Crear serie
   *
   * Crea una nueva serie de folios para la organización.
   * Las series son útiles para llevar un control de los folios emitidos para cada tipo de factura.
   *
   */
  createSeriesGroup(
    organization_id: string,
    seriesData: OperationBody<'createSeriesGroup'>,
  ): Promise<OperationResponse<'createSeriesGroup'>> {
    if (!organization_id)
      return Promise.reject(new Error('organization_id is required'))

    return this.client.request<OperationResponse<'createSeriesGroup'>>(
      `/organizations/${encodeURIComponent(organization_id)}/series-group`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createSeriesGroup,
        body: seriesData,
      },
    )
  }

  /**
   * Editar serie
   *
   * Edita el número de foliaje de la serie en ambientes Test y Live de la organización.
   *
   */
  updateSeriesGroup(
    organization_id: string,
    seriesName: string,
    data: OperationBody<'updateSeriesGroup'>,
  ): Promise<OperationResponse<'updateSeriesGroup'>> {
    if (!organization_id)
      return Promise.reject(new Error('organization_id is required'))
    if (!seriesName) return Promise.reject(new Error('seriesName is required'))

    return this.client.request<OperationResponse<'updateSeriesGroup'>>(
      `/organizations/${encodeURIComponent(organization_id)}/series-group/${encodeURIComponent(seriesName)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateSeriesGroup,
        body: data,
      },
    )
  }

  /**
   * Establecer serie predeterminada
   *
   * Asigna una serie predeterminada para el tipo de comprobante indicado.
   *
   */
  updateDefaultSeries(
    organization_id: string,
    data: OperationBody<'updateDefaultSeries'>,
  ): Promise<OperationResponse<'updateDefaultSeries'>> {
    if (!organization_id)
      return Promise.reject(new Error('organization_id is required'))

    return this.client.request<OperationResponse<'updateDefaultSeries'>>(
      `/organizations/${encodeURIComponent(organization_id)}/series-group/default-series`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateDefaultSeries,
        body: data,
      },
    )
  }

  /**
   * Eliminar serie
   *
   * Elimina la serie previamente creada
   *
   */
  deleteSeriesGroup(
    organization_id: string,
    seriesName: string,
  ): Promise<OperationResponse<'deleteSeriesGroup'>> {
    if (!organization_id)
      return Promise.reject(new Error('organization_id is required'))
    if (!seriesName) return Promise.reject(new Error('seriesName is required'))

    return this.client.request<OperationResponse<'deleteSeriesGroup'>>(
      `/organizations/${encodeURIComponent(organization_id)}/series-group/${encodeURIComponent(seriesName)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteSeriesGroup },
    )
  }

  /**
   * Detalle de organización
   *
   * Retorna el detalle de la organización actualmente autenticada.
   *
   */
  me(): Promise<OperationResponse<'meOrganization'>> {
    return this.client.request<OperationResponse<'meOrganization'>>(
      `/organizations/me`,
      { method: 'GET', datePlan: operationDatePlans.meOrganization },
    )
  }

  /**
   * Editar config. autofactura
   *
   * Actualiza la configuración del portal de autofactura de la organización.
   *
   */
  updateSelfInvoiceSettings(
    id: string,
    data: OperationBody<'editOrganizationSelfInvoiceSettings'>,
  ): Promise<OperationResponse<'editOrganizationSelfInvoiceSettings'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<
      OperationResponse<'editOrganizationSelfInvoiceSettings'>
    >(`/organizations/${encodeURIComponent(id)}/self-invoice`, {
      method: 'PUT',
      datePlan: operationDatePlans.editOrganizationSelfInvoiceSettings,
      body: data,
    })
  }

  /**
   * Listar usuarios con acceso a organización
   *
   * Regresa un arreglo con los usuarios que actualmente tienen acceso a la organización, incluyendo al propietario. Este endpoint no está paginado.
   */
  listTeamAccess(
    organizationId: string,
  ): Promise<OperationResponse<'getOrganizationTeam'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<OperationResponse<'getOrganizationTeam'>>(
      `/organizations/${encodeURIComponent(organizationId)}/team`,
      { method: 'GET', datePlan: operationDatePlans.getOrganizationTeam },
    )
  }

  /**
   * Obtener acceso de usuario
   *
   * Regresa el detalle del acceso del usuario dentro de la organización usando su `access_id`, incluyendo accesos implícitos como el del propietario.
   */
  retrieveTeamAccess(
    organizationId: string,
    accessId: string,
  ): Promise<OperationResponse<'getOrganizationTeamUser'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!accessId) return Promise.reject(new Error('accessId is required'))

    return this.client.request<OperationResponse<'getOrganizationTeamUser'>>(
      `/organizations/${encodeURIComponent(organizationId)}/team/${encodeURIComponent(accessId)}`,
      { method: 'GET', datePlan: operationDatePlans.getOrganizationTeamUser },
    )
  }

  /**
   * Reasignar rol a usuario
   */
  updateTeamAccessRole(
    organizationId: string,
    accessId: string,
    role: OperationBody<'updateOrganizationTeamUserRole'>['role'],
  ): Promise<OperationResponse<'updateOrganizationTeamUserRole'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!accessId) return Promise.reject(new Error('accessId is required'))

    return this.client.request<
      OperationResponse<'updateOrganizationTeamUserRole'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/${encodeURIComponent(accessId)}/role`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateOrganizationTeamUserRole,
        body: { role: role },
      },
    )
  }

  /**
   * Eliminar usuario con acceso
   */
  removeTeamAccess(
    organizationId: string,
    accessId: string,
  ): Promise<OperationResponse<'removeOrganizationUserAccess'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!accessId) return Promise.reject(new Error('accessId is required'))

    return this.client.request<
      OperationResponse<'removeOrganizationUserAccess'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/${encodeURIComponent(accessId)}`,
      {
        method: 'DELETE',
        datePlan: operationDatePlans.removeOrganizationUserAccess,
      },
    )
  }

  /**
   * Listar invitaciones enviadas
   *
   * Regresa invitaciones enviadas desde la organización.
   */
  listSentTeamInvites(
    organizationId: string,
  ): Promise<OperationResponse<'listOrganizationTeamInvites'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'listOrganizationTeamInvites'>
    >(`/organizations/${encodeURIComponent(organizationId)}/team/invites`, {
      method: 'GET',
      datePlan: operationDatePlans.listOrganizationTeamInvites,
    })
  }

  /**
   * Invitar usuario a organización
   *
   * Crea o actualiza una invitación de usuario. Por defecto, el acceso es de administrador con permisos completos; para limitarlo, crea un rol y envía su ID en `role`.
   *
   * Cada organización puede invitar a un usuario sin costo adicional. A partir del segundo usuario invitado, cada usuario adicional tendrá un costo mensual. Este cargo se aplica automáticamente cuando el usuario acepta la invitación.
   * Puedes consultar el precio vigente en nuestra [página de precios](https://www.facturapi.io/pricing).
   *
   */
  inviteUserToTeam(
    organizationId: string,
    data: OperationBody<'createOrganizationTeamInvite'>,
  ): Promise<OperationResponse<'createOrganizationTeamInvite'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'createOrganizationTeamInvite'>
    >(`/organizations/${encodeURIComponent(organizationId)}/team/invites`, {
      method: 'POST',
      datePlan: operationDatePlans.createOrganizationTeamInvite,
      body: data,
    })
  }

  /**
   * Cancelar invitación enviada
   *
   * Elimina una invitación pendiente de la organización.
   */
  cancelTeamInvite(
    organizationId: string,
    inviteKey: string,
  ): Promise<OperationResponse<'deleteOrganizationTeamInvite'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!inviteKey) return Promise.reject(new Error('inviteKey is required'))

    return this.client.request<
      OperationResponse<'deleteOrganizationTeamInvite'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/invites/${encodeURIComponent(inviteKey)}`,
      {
        method: 'DELETE',
        datePlan: operationDatePlans.deleteOrganizationTeamInvite,
      },
    )
  }

  /**
   * Listar invitaciones recibidas
   *
   * Regresa las invitaciones recibidas para el usuario autenticado.
   */
  listReceivedTeamInvites(): Promise<
    OperationResponse<'listPendingOrganizationInvites'>
  > {
    return this.client.request<
      OperationResponse<'listPendingOrganizationInvites'>
    >(`/organizations/invites/pending`, {
      method: 'GET',
      datePlan: operationDatePlans.listPendingOrganizationInvites,
    })
  }

  /**
   * Responder invitación
   *
   * Acepta o rechaza una invitación usando su `invite_key`.
   */
  respondTeamInvite(
    inviteKey: string,
    data: OperationBody<'respondOrganizationInvite'>,
  ): Promise<OperationResponse<'respondOrganizationInvite'>> {
    if (!inviteKey) return Promise.reject(new Error('inviteKey is required'))

    return this.client.request<OperationResponse<'respondOrganizationInvite'>>(
      `/organizations/invites/${encodeURIComponent(inviteKey)}/response`,
      {
        method: 'POST',
        datePlan: operationDatePlans.respondOrganizationInvite,
        body: data,
      },
    )
  }

  /**
   * Listar roles de organización
   */
  listTeamRoles(
    organizationId: string,
  ): Promise<OperationResponse<'listOrganizationPermissionRoles'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'listOrganizationPermissionRoles'>
    >(`/organizations/${encodeURIComponent(organizationId)}/team/roles`, {
      method: 'GET',
      datePlan: operationDatePlans.listOrganizationPermissionRoles,
    })
  }

  /**
   * Listar plantillas de roles
   */
  listTeamRoleTemplates(
    organizationId: string,
  ): Promise<OperationResponse<'listOrganizationPermissionRoleTemplates'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'listOrganizationPermissionRoleTemplates'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/roles/templates`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listOrganizationPermissionRoleTemplates,
      },
    )
  }

  /**
   * Listar operaciones de permisos
   */
  listTeamRoleOperations(
    organizationId: string,
  ): Promise<OperationResponse<'listOrganizationPermissionOperations'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'listOrganizationPermissionOperations'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/roles/operations`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listOrganizationPermissionOperations,
      },
    )
  }

  /**
   * Obtener rol de organización
   */
  retrieveTeamRole(
    organizationId: string,
    roleId: string,
  ): Promise<OperationResponse<'getOrganizationPermissionRole'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!roleId) return Promise.reject(new Error('roleId is required'))

    return this.client.request<
      OperationResponse<'getOrganizationPermissionRole'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/roles/${encodeURIComponent(roleId)}`,
      {
        method: 'GET',
        datePlan: operationDatePlans.getOrganizationPermissionRole,
      },
    )
  }

  /**
   * Crear rol de organización
   */
  createTeamRole(
    organizationId: string,
    data: OperationBody<'createOrganizationPermissionRole'>,
  ): Promise<OperationResponse<'createOrganizationPermissionRole'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))

    return this.client.request<
      OperationResponse<'createOrganizationPermissionRole'>
    >(`/organizations/${encodeURIComponent(organizationId)}/team/roles`, {
      method: 'POST',
      datePlan: operationDatePlans.createOrganizationPermissionRole,
      body: data,
    })
  }

  /**
   * Actualizar rol de organización
   */
  updateTeamRole(
    organizationId: string,
    roleId: string,
    data: OperationBody<'updateOrganizationPermissionRole'>,
  ): Promise<OperationResponse<'updateOrganizationPermissionRole'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!roleId) return Promise.reject(new Error('roleId is required'))

    return this.client.request<
      OperationResponse<'updateOrganizationPermissionRole'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/roles/${encodeURIComponent(roleId)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateOrganizationPermissionRole,
        body: data,
      },
    )
  }

  /**
   * Eliminar rol de organización
   */
  deleteTeamRole(
    organizationId: string,
    roleId: string,
  ): Promise<OperationResponse<'deleteOrganizationPermissionRole'>> {
    if (!organizationId)
      return Promise.reject(new Error('organizationId is required'))
    if (!roleId) return Promise.reject(new Error('roleId is required'))

    return this.client.request<
      OperationResponse<'deleteOrganizationPermissionRole'>
    >(
      `/organizations/${encodeURIComponent(organizationId)}/team/roles/${encodeURIComponent(roleId)}`,
      {
        method: 'DELETE',
        datePlan: operationDatePlans.deleteOrganizationPermissionRole,
      },
    )
  }

  /**
   * Subir certificado FIEL
   *
   * Sube los archivos de la e.firma (FIEL) de la organización.
   *
   * La e.firma (FIEL) no es necesaria para crear CFDI. Para timbrar CFDI
   * solo necesitas cargar el Certificado de Sello Digital (CSD). La FIEL es
   * necesaria para utilizar la descarga masiva de CFDI.
   *
   */
  async uploadFiel(
    id: string,
    cerFile: BinaryInput,
    keyFile: BinaryInput,
    password: string,
  ): Promise<OperationResponse<'uploadOrganizationFiel'>> {
    if (!id) return Promise.reject(new Error('id is required'))
    if (typeof FormData === 'undefined')
      throw new Error(
        'FormData is not available in this runtime. Use Node.js 18+ or provide a FormData implementation.',
      )
    const formData = new FormData()
    const [cer, key] = await Promise.all([
      prepareFile(cerFile, 'application/octet-stream'),
      prepareFile(keyFile, 'application/octet-stream'),
    ])
    formData.append('cer', cer, 'cer.cer')
    formData.append('key', key, 'key.key')
    formData.append('password', password)
    return this.client.request<OperationResponse<'uploadOrganizationFiel'>>(
      `/organizations/${encodeURIComponent(id)}/fiel`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.uploadOrganizationFiel,
        formData,
      },
    )
  }
}
