// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Products {
  constructor(public client: WrapperClient) {}
  /**
   * Crear producto
   *
   * Registra un nuevo producto o servicio en tu catálogo de Facturapi.
   *
   * Puedes usar el ID del producto para crear facturas sin tener que enviar todos los datos del producto cada vez.
   *
   * Te en cuenta que los productos que crees en ambiente _Test_ **no se
   * comparten** con el ambiente _Live_.
   *
   */
  create(
    data: OperationBody<'createProduct'>,
  ): Promise<OperationResponse<'createProduct'>> {
    return this.client.request<OperationResponse<'createProduct'>>(
      `/products`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createProduct,
        body: data,
      },
    )
  }

  /**
   * Listar productos
   *
   * Regresa una lista paginada de todos los productos de una organización o realiza una búsqueda de acuerdo a parámetros
   */
  list(
    params?: OperationQuery<'listProducts'> | null,
  ): Promise<OperationResponse<'listProducts'>> {
    return this.client.request<OperationResponse<'listProducts'>>(`/products`, {
      method: 'GET',
      datePlan: operationDatePlans.listProducts,
      params: params,
    })
  }

  /**
   * Obtener producto por ID
   *
   * Regresa el objeto `Product` relacionado al `id` especificado.
   */
  retrieve(id: string): Promise<OperationResponse<'getProduct'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getProduct'>>(
      `/products/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getProduct },
    )
  }

  /**
   * Editar producto
   *
   * Actualiza la información de un producto existente, asignando los valores de los parámetros enviados. Los parámetros que no se envíen en la petición no se modificarán.
   */
  update(
    id: string,
    data: OperationBody<'editProduct'>,
  ): Promise<OperationResponse<'editProduct'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'editProduct'>>(
      `/products/${encodeURIComponent(id)}`,
      { method: 'PUT', datePlan: operationDatePlans.editProduct, body: data },
    )
  }

  /**
   * Eliminar producto
   *
   * Elimina el producto de tu organización. Las facturas asociadas al producto **no** se eliminarán.
   */
  del(id: string): Promise<OperationResponse<'deleteProduct'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'deleteProduct'>>(
      `/products/${encodeURIComponent(id)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteProduct },
    )
  }
}
