// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
import type { components as OutputComponents } from '../generated/output'
export default class Receipts {
  constructor(public client: WrapperClient) {}
  /**
   * Crear recibo
   *
   * Crea un nuevo Recibo, el cual funge como nota de venta.
   *
   * Todos los recibos generan una URL de autofactura que cliente puede
   * visitar para llenar sus datos fiscales en un micrositio con el branding
   * de la organización.
   *
   * @param data - Datos de la solicitud.
   * @returns Nuevo objeto `Receipt` creado
   */
  create(
    data: OperationBody<'createReceipt'>,
  ): Promise<OperationResponse<'createReceipt'>> {
    return this.client.request<OperationResponse<'createReceipt'>>(
      `/receipts`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createReceipt,
        body: data,
      },
    )
  }

  /**
   * Listar recibos
   *
   * Regresa una lista paginada de todos los recibos de una organización o realiza una búsqueda de acuerdo a parámetros
   *
   * @param params - Parámetros de consulta.
   * @returns Resultado de la búsqueda
   */
  list(
    params?: OperationQuery<'listReceipts'> | null,
  ): Promise<OperationResponse<'listReceipts'>> {
    return this.client.request<OperationResponse<'listReceipts'>>(`/receipts`, {
      method: 'GET',
      datePlan: operationDatePlans.listReceipts,
      params: params,
    })
  }

  /**
   * Obtener recibo por ID
   *
   * Regresa el objeto 'Receipt' relacionado al `id` especificado.
   *
   * @param id - ID del objeto a obtener
   * @returns Objeto `Receipt`
   */
  retrieve(id: string): Promise<OperationResponse<'getReceipt'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getReceipt'>>(
      `/receipts/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getReceipt },
    )
  }

  /**
   * Facturar recibo
   *
   * Crea una factura a partir de un recibo.
   *
   * Sólo pueden facturarse recibos abiertos (`status = "open"`)
   *
   * Si envías `customer`, ese cliente se usará como receptor de la factura y
   * sobrescribirá el cliente asignado al recibo. Si omites `customer`, el
   * recibo debe tener un cliente asignado previamente.
   *
   * Una vez facturado, el `status` del recibo cambiará a `"invoiced_to_customer"`.
   *
   * @param id - ID del recibo a facturar
   * @param data - Datos de la solicitud.
   * @returns Nuevo objeto `Invoice` creado
   */
  invoice(
    id: string,
    data: OperationBody<'invoiceReceipt'>,
  ): Promise<OperationResponse<'invoiceReceipt'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'invoiceReceipt'>>(
      `/receipts/${encodeURIComponent(id)}/invoice`,
      {
        method: 'POST',
        datePlan: operationDatePlans.invoiceReceipt,
        body: data,
      },
    )
  }

  /**
   * Crear factura global
   *
   * Crea una factura global que incluirá todos los recibos con `status = “open”` de un cierto periodo.
   *
   * La factura global se emite al cliente genérico `PUBLICO EN GENERAL`.
   * Los recibos incluidos quedan asociados a ese cliente y su `status`
   * cambia a `"invoiced_globally"`.
   *
   * Una factura global puede incluir hasta 5,000 recibos abiertos. Si el periodo
   * contiene más, puedes enviar `limit_to_max_receipts: true` y repetir la solicitud
   * con el mismo periodo hasta recibir `null`.
   *
   * @param data - Datos de la solicitud.
   * @returns Nuevo objeto `Invoice` creado, o `null` si no hay recibos abiertos en el periodo
   */
  createGlobalInvoice(
    data: OperationBody<'createGlobalInvoice'>,
  ): Promise<OperationResponse<'createGlobalInvoice'>> {
    return this.client.request<OperationResponse<'createGlobalInvoice'>>(
      `/receipts/global-invoice`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createGlobalInvoice,
        body: data,
      },
    )
  }

  /**
   * Facturar múltiples recibos
   *
   * Crea una sola factura a partir de múltiples recibos seleccionados por su `key`.
   *
   * Si envías `customer`, ese cliente se usará como receptor de la factura y
   * sobrescribirá el cliente asignado a los recibos incluidos. Si omites
   * `customer`, todos los recibos deben tener asignado el mismo cliente.
   * También se validará el campo `address` de los recibos incluidos.
   *
   * Si `dry_run` es `true`, no crea la factura y regresa un resumen de vista previa.
   * El `dry_run` valida las mismas reglas que la creación real, pero no persiste cambios.
   *
   * @param data - Datos de la solicitud.
   * @returns Objeto `Invoice` creado u objeto resumen cuando `dry_run=true`
   */
  toInvoice(
    data: OperationBody<'createToInvoiceFromReceipts'> & { dry_run: true },
  ): Promise<OutputComponents['schemas']['ToInvoiceSummary']>

  /**
   * Facturar múltiples recibos
   *
   * Crea una sola factura a partir de múltiples recibos seleccionados por su `key`.
   *
   * Si envías `customer`, ese cliente se usará como receptor de la factura y
   * sobrescribirá el cliente asignado a los recibos incluidos. Si omites
   * `customer`, todos los recibos deben tener asignado el mismo cliente.
   * También se validará el campo `address` de los recibos incluidos.
   *
   * Si `dry_run` es `true`, no crea la factura y regresa un resumen de vista previa.
   * El `dry_run` valida las mismas reglas que la creación real, pero no persiste cambios.
   *
   * @param data - Datos de la solicitud.
   * @returns Objeto `Invoice` creado u objeto resumen cuando `dry_run=true`
   */
  toInvoice(
    data: OperationBody<'createToInvoiceFromReceipts'> & { dry_run?: false },
  ): Promise<OutputComponents['schemas']['Invoice']>

  /**
   * Facturar múltiples recibos
   *
   * Crea una sola factura a partir de múltiples recibos seleccionados por su `key`.
   *
   * Si envías `customer`, ese cliente se usará como receptor de la factura y
   * sobrescribirá el cliente asignado a los recibos incluidos. Si omites
   * `customer`, todos los recibos deben tener asignado el mismo cliente.
   * También se validará el campo `address` de los recibos incluidos.
   *
   * Si `dry_run` es `true`, no crea la factura y regresa un resumen de vista previa.
   * El `dry_run` valida las mismas reglas que la creación real, pero no persiste cambios.
   *
   * @param data - Datos de la solicitud.
   * @returns Objeto `Invoice` creado u objeto resumen cuando `dry_run=true`
   */
  toInvoice(
    data: OperationBody<'createToInvoiceFromReceipts'>,
  ): Promise<OperationResponse<'createToInvoiceFromReceipts'>>

  /**
   * Facturar múltiples recibos
   *
   * Crea una sola factura a partir de múltiples recibos seleccionados por su `key`.
   *
   * Si envías `customer`, ese cliente se usará como receptor de la factura y
   * sobrescribirá el cliente asignado a los recibos incluidos. Si omites
   * `customer`, todos los recibos deben tener asignado el mismo cliente.
   * También se validará el campo `address` de los recibos incluidos.
   *
   * Si `dry_run` es `true`, no crea la factura y regresa un resumen de vista previa.
   * El `dry_run` valida las mismas reglas que la creación real, pero no persiste cambios.
   *
   * @param data - Datos de la solicitud.
   * @returns Objeto `Invoice` creado u objeto resumen cuando `dry_run=true`
   */
  toInvoice(
    data: OperationBody<'createToInvoiceFromReceipts'>,
  ): Promise<OperationResponse<'createToInvoiceFromReceipts'>> {
    return this.client.request<
      OperationResponse<'createToInvoiceFromReceipts'>
    >(`/receipts/to-invoice`, {
      method: 'POST',
      datePlan: operationDatePlans.createToInvoiceFromReceipts,
      body: data,
    })
  }

  /**
   * Vista previa PDF de factura múltiple
   *
   * Genera una vista previa en PDF para una factura construida a partir de múltiples recibos seleccionados por `key`.
   *
   * La vista previa valida las mismas reglas de cliente que la creación real:
   * si omites `customer`, todos los recibos deben tener asignado el mismo cliente.
   *
   * @param data - Datos de la solicitud.
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  previewToInvoicePdf(
    data: OperationBody<'previewToInvoiceFromReceipts'>,
  ): Promise<OperationResponse<'previewToInvoiceFromReceipts'>> {
    return this.client.request<
      OperationResponse<'previewToInvoiceFromReceipts'>
    >(`/receipts/to-invoice/preview`, {
      method: 'POST',
      datePlan: operationDatePlans.previewToInvoiceFromReceipts,
      body: data,
    })
  }

  /**
   * Obtener URL del preview de factura de recibos
   *
   * Devuelve un objeto con los metadatos del archivo y una URL temporal para el preview PDF de una factura construida con los recibos seleccionados.
   *
   * @param data - Datos de la solicitud.
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  previewToInvoicePdfUrl(
    data: OperationBody<'previewToInvoiceFromReceiptsUrl'>,
  ): Promise<OperationResponse<'previewToInvoiceFromReceiptsUrl'>> {
    return this.client.request<
      OperationResponse<'previewToInvoiceFromReceiptsUrl'>
    >(`/receipts/to-invoice/preview/download-url`, {
      method: 'POST',
      datePlan: operationDatePlans.previewToInvoiceFromReceiptsUrl,
      body: data,
    })
  }

  /**
   * Cancelar recibo
   *
   * Marca un recibo como cancelado, cambiando su propiedad `status` a `"canceled"`.
   *
   * Una vez cancelado, el recibo no podrá ser facturado.
   *
   * @param id - ID del recibo a cancelar
   * @returns Objeto 'Receipt' cancelado exitosamente
   */
  cancel(id: string): Promise<OperationResponse<'cancelReceipt'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'cancelReceipt'>>(
      `/receipts/${encodeURIComponent(id)}`,
      { method: 'DELETE', datePlan: operationDatePlans.cancelReceipt },
    )
  }

  /**
   * Enviar recibo por correo electrónico
   *
   * Envía un correo electrónico a la dirección de tu cliente.
   *
   * El correo enviado estará personalizado con el logotipo y los colores de la organización que lo creó,
   * e incluirá un botón para facturar el recibo, así con el recibo en formato PDF adjunto al mensaje.
   *
   * @param id - ID del objeto a obtener
   * @param data - Datos de la solicitud.
   * @returns Objeto genérico de respuesta
   */
  sendByEmail(
    id: string,
    data?: OperationBody<'sendReceiptByEmail'>,
  ): Promise<OperationResponse<'sendReceiptByEmail'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'sendReceiptByEmail'>>(
      `/receipts/${encodeURIComponent(id)}/email`,
      {
        method: 'POST',
        datePlan: operationDatePlans.sendReceiptByEmail,
        body: data,
      },
    )
  }

  /**
   * Descargar PDF
   *
   * Descarga el recibo digital en formato PDF.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadPdf(id: string): Promise<OperationResponse<'downloadReceiptPdf'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadReceiptPdf'>>(
      `/receipts/${encodeURIComponent(id)}/pdf`,
      { method: 'GET', datePlan: operationDatePlans.downloadReceiptPdf },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un objeto con los metadatos del archivo y un enlace temporal para descargar el recibo digital en PDF, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Objeto SignedDownloadUrl con url, expires_at, content_type y filename.
   */
  downloadPdfUrl(
    id: string,
  ): Promise<OperationResponse<'getReceiptDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getReceiptDownloadUrl'>>(
      `/receipts/${encodeURIComponent(id)}/download-url/pdf`,
      { method: 'GET', datePlan: operationDatePlans.getReceiptDownloadUrl },
    )
  }

  /**
   * Asignar o reasignar cliente a recibo
   *
   * Asigna o reasigna un cliente existente (por ID) a un recibo, o crea uno nuevo enviando el objeto del cliente.
   *
   * @param id - ID del recibo a actualizar
   * @param data - Datos de la solicitud.
   * @returns Objeto `Receipt` actualizado
   */
  updateCustomer(
    id: string,
    data: OperationBody<'assignReceiptCustomer'>,
  ): Promise<OperationResponse<'assignReceiptCustomer'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'assignReceiptCustomer'>>(
      `/receipts/${encodeURIComponent(id)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.assignReceiptCustomer,
        body: data,
      },
    )
  }
}
