// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Retentions {
  constructor(public client: WrapperClient) {}
  /**
   * Crear retención
   *
   * Crea una nueva Retención. Si el comprobante es creado en ambiente Live, ésta será **timbrado y enviado al SAT**.
   *
   * Para crear una retención en borrador, envía `status: "draft"`. En ese caso,
   * la retención se guardará sin timbrarse, no se enviará al PAC y podrá estar
   * incompleta. Facturapi asignará `is_ready_to_stamp: true` únicamente cuando
   * el borrador tenga todos los datos requeridos para timbrarse.
   *
   * @param data - Datos de la solicitud.
   * @returns Nuevo objeto `Retention` creado
   */
  create(
    data: OperationBody<'createRetention'>,
  ): Promise<OperationResponse<'createRetention'>> {
    return this.client.request<OperationResponse<'createRetention'>>(
      `/retentions`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createRetention,
        body: data,
      },
    )
  }

  /**
   * Listar retenciones
   *
   * Regresa una lista paginada de todas las retenciones de una organización o realiza una búsqueda de acuerdo a parámetros
   *
   * @param params - Parámetros de consulta.
   * @returns Resultado de la búsqueda
   */
  list(
    params?: OperationQuery<'listRetentions'> | null,
  ): Promise<OperationResponse<'listRetentions'>> {
    return this.client.request<OperationResponse<'listRetentions'>>(
      `/retentions`,
      {
        method: 'GET',
        datePlan: operationDatePlans.listRetentions,
        params: params,
      },
    )
  }

  /**
   * Obtener retención por ID
   *
   * Regresa el objeto 'Retention' relacionado al `id` especificado.
   *
   * @param id - ID del objeto a obtener
   * @returns Objeto `Retention`
   */
  retrieve(id: string): Promise<OperationResponse<'getRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getRetention'>>(
      `/retentions/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getRetention },
    )
  }

  /**
   * Cancelar retención
   *
   * Realiza una solicitud de cancelación de retención ante el SAT.
   *
   * A diferencia de las facturas comunes, la cancelación de la retención es inmediata y no requiere autorización de parte del receptor.
   *
   * Si el status de la retención es `draft`, este método la eliminará de la
   * base de datos sin llamar al SAT/PAC y sin requerir parámetros de cancelación.
   *
   * @param id - ID de la retención a cancelar
   * @param params - Parámetros de consulta.
   * @returns Objeto `Retention` cancelado exitosamente
   */
  cancel(
    id: string,
    params?: OperationQuery<'cancelRetention'>,
  ): Promise<OperationResponse<'cancelRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'cancelRetention'>>(
      `/retentions/${encodeURIComponent(id)}`,
      {
        method: 'DELETE',
        datePlan: operationDatePlans.cancelRetention,
        params: params,
      },
    )
  }

  /**
   * Editar borrador de retención
   *
   * Actualiza la información de una retención con status `draft`, asignando
   * los valores de los parámetros enviados. Los parámetros que no se envíen
   * en la petición no se modificarán.
   *
   * Facturapi recalculará automáticamente `is_ready_to_stamp` después de cada
   * edición. Si la retención ya no está en status `draft`, la llamada regresará
   * un error.
   *
   * @param id - ID de la retención a editar
   * @param data - Datos de la solicitud.
   * @returns Objeto `Retention` editado correctamente
   */
  updateDraft(
    id: string,
    data: OperationBody<'updateDraftRetention'>,
  ): Promise<OperationResponse<'updateDraftRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'updateDraftRetention'>>(
      `/retentions/${encodeURIComponent(id)}`,
      {
        method: 'PUT',
        datePlan: operationDatePlans.updateDraftRetention,
        body: data,
      },
    )
  }

  /**
   * Timbrar borrador de retención
   *
   * Timbra una retención con status `draft` y la envía al SAT para su validación.
   *
   * Facturapi validará el borrador como una retención completa antes de timbrarlo.
   * Si el borrador está incompleto o no es válido, la llamada regresará un error.
   *
   * @param id - ID de la retención a timbrar
   * @returns Objeto `Retention` timbrado correctamente
   */
  stampDraft(id: string): Promise<OperationResponse<'stampDraftRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'stampDraftRetention'>>(
      `/retentions/${encodeURIComponent(id)}/stamp`,
      { method: 'POST', datePlan: operationDatePlans.stampDraftRetention },
    )
  }

  /**
   * Copiar a borrador
   *
   * Crea una copia en borrador de la retención especificada. La copia no conserva
   * campos propios del timbrado, cancelación, idempotencia o identidad externa.
   *
   * @param id - ID de la retención a copiar
   * @returns Nuevo objeto `Retention` con status `draft`.
   */
  copyToDraft(id: string): Promise<OperationResponse<'copyToDraftRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'copyToDraftRetention'>>(
      `/retentions/${encodeURIComponent(id)}/copy`,
      { method: 'POST', datePlan: operationDatePlans.copyToDraftRetention },
    )
  }

  /**
   * Enviar retención por correo electrónico
   *
   * Envía un correo electrónico a la dirección de tu cliente, con los archivos XML y PDF adjuntos al mensaje.
   *
   * @param id - ID del objeto a obtener
   * @param data - Datos de la solicitud.
   * @returns Objeto genérico de respuesta
   */
  sendByEmail(
    id: string,
    data?: OperationBody<'sendRetentionByEmail'>,
  ): Promise<OperationResponse<'sendRetentionByEmail'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'sendRetentionByEmail'>>(
      `/retentions/${encodeURIComponent(id)}/email`,
      {
        method: 'POST',
        datePlan: operationDatePlans.sendRetentionByEmail,
        body: data,
      },
    )
  }

  /**
   * Descargar retención
   *
   * Descarga una retención en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadPdf(id: string): Promise<OperationResponse<'downloadRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadRetention'>>(
      `/retentions/${encodeURIComponent(id)}/pdf`,
      { method: 'GET', datePlan: operationDatePlans.downloadRetention },
    )
  }

  /**
   * Descargar retención
   *
   * Descarga una retención en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadXml(id: string): Promise<OperationResponse<'downloadRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadRetention'>>(
      `/retentions/${encodeURIComponent(id)}/xml`,
      { method: 'GET', datePlan: operationDatePlans.downloadRetention },
    )
  }

  /**
   * Descargar retención
   *
   * Descarga una retención en PDF, XML o ambos en un archivo comprimido ZIP.
   *
   * @param id - ID del objeto a descargar
   * @returns Archivo como stream en Node.js o Blob en el navegador.
   */
  downloadZip(id: string): Promise<OperationResponse<'downloadRetention'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'downloadRetention'>>(
      `/retentions/${encodeURIComponent(id)}/zip`,
      { method: 'GET', datePlan: operationDatePlans.downloadRetention },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la retención en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Enlace temporal de descarga de la retención en el formato solicitado
   */
  downloadPdfUrl(
    id: string,
  ): Promise<OperationResponse<'getRetentionDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getRetentionDownloadUrl'>>(
      `/retentions/${encodeURIComponent(id)}/download-url/pdf`,
      { method: 'GET', datePlan: operationDatePlans.getRetentionDownloadUrl },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la retención en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Enlace temporal de descarga de la retención en el formato solicitado
   */
  downloadXmlUrl(
    id: string,
  ): Promise<OperationResponse<'getRetentionDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getRetentionDownloadUrl'>>(
      `/retentions/${encodeURIComponent(id)}/download-url/xml`,
      { method: 'GET', datePlan: operationDatePlans.getRetentionDownloadUrl },
    )
  }

  /**
   * Obtener enlace de descarga
   *
   * Devuelve un enlace temporal para descargar la retención en PDF, XML o ambos en un archivo comprimido ZIP, sin que el archivo pase por tu servidor.
   *
   * El enlace da acceso a ese archivo mientras siga vigente: trátalo como una credencial y no lo almacenes.
   *
   * @param id - ID del objeto a descargar
   * @returns Enlace temporal de descarga de la retención en el formato solicitado
   */
  downloadZipUrl(
    id: string,
  ): Promise<OperationResponse<'getRetentionDownloadUrl'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getRetentionDownloadUrl'>>(
      `/retentions/${encodeURIComponent(id)}/download-url/zip`,
      { method: 'GET', datePlan: operationDatePlans.getRetentionDownloadUrl },
    )
  }
}
