// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type Address = Output['CommonAddressProperties']
export type InvoiceItemPart = Output['Parts']
export type InvoiceItemThirdParty = Output['ThirdParty']
export type Tax = Output['BaseTax'] | Output['IepsTax']
export type LocalTax = Output['LocalTax']
export type ProductInfo = Output['LineItemProduct']
export type CustomerInfo = Output['CustomerInfo']
export type InvoiceItem = Output['LineItem']
export type XmlNamespace = Output['NamespaceProperties']
export type RelatedDocument = Output['RelatedDocument']
export type GenericResponse = Output['OkResponse']
export type SendEmailBody = OperationBody<'sendInvoiceByEmail'>
export type SignedDownloadUrl = Output['SignedDownloadUrl']
export * from './runtime'
export type SearchResult<T> = Output['SearchResult'] & { data: T[] }
export type PageSearchParams = ({ pagination?: 'page' } | { page: number }) &
  Record<string, unknown>
export type CursorSearchParams = (
  { pagination: 'cursor' } | { after: string } | { before: string }
) &
  Record<string, unknown>
