// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type PagoComplementData = Output['PaymentProperties']
export type PaymentRelatedDocument = NonNullable<
  PagoComplementData['related_documents']
>[number]
export type PaymentRelatedDocumentTax = NonNullable<
  PaymentRelatedDocument['taxes']
>[number]
export type NominaReceptor = Output['NominaReceptorProperties']
export type NominaComplementData = Output['NominaComplementDataProperties']
