// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type TaxInfoValidation = OperationResponse<'validateCustomerTaxInfo'>
export type TaxInfoValidationError = TaxInfoValidation['errors'][number]
export type Customer = Output['Customer']
