// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type GlobalInfo = NonNullable<Output['InvoiceProperties']['global']>
export type InvoiceComplement = NonNullable<
  Output['InvoiceProperties']['complements']
>[number]
export type Invoice = Output['Invoice']
export type CancelInvoiceOptions = Input['CancellationQueryInput']
export type CreateZipRequestData = OperationBody<'createInvoiceZipRequest'>
export type ListZipRequestsParams = OperationQuery<'listInvoiceZipRequests'>
export type ZipRequest = Output['InvoiceZipRequest']
export type PaymentSummaryParams = OperationQuery<'getInvoicePaymentSummary'>
export type PaymentSummary = OperationResponse<'getInvoicePaymentSummary'>
export type PaymentSummaryTax = NonNullable<PaymentSummary['taxes']>[number]
