// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type Series = Output['OrganizationSeriesGroup']
export type OrganizationDefaultSeriesUpdateInput =
  Input['OrganizationSeriesDefaultInput']
export type ApiKeys = OperationResponse<'listLiveApiKeys'>[number]
export type OrganizationUserAccess = Output['OrganizationUserAccess']
export type OrganizationInvite = Output['OrganizationInvite']
export type OrganizationInviteCreateInput =
  Input['OrganizationInviteCreateInput']
export type OrganizationInviteResponseInput =
  Input['OrganizationInviteRespondInput']
export type OrganizationTeamRole = Output['OrganizationPermissionRole']
export type OrganizationTeamRoleCreateInput =
  Input['OrganizationPermissionRoleCreateInput']
export type OrganizationTeamRoleUpdateInput =
  Input['OrganizationPermissionRoleUpdateInput']
export type OrganizationTeamRoleTemplate =
  Output['OrganizationPermissionRoleTemplate']
export type Organization = Output['Organization']
