// Generated by pnpm generate:sdk. Do not edit directly.
import type { components as InputComponents } from '../generated/input'
import type { components as OutputComponents } from '../generated/output'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
type Input = InputComponents['schemas']
type Output = OutputComponents['schemas']
export type Receipt = Output['Receipt']
export type ReceiptsToInvoiceInput = Input['ToInvoiceInput']
export type PreviewReceiptsToInvoicePdfInput = Input['ToInvoicePreviewInput']
