import assert from 'node:assert/strict'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import ts from 'typescript'
import prettier from 'prettier'
import { compileDatePlans } from './sdk/date-plans.mjs'
import { resolveOperationBinding } from './sdk/operation-bindings.mjs'
import { readSpecification } from './sdk/openapi-source.mjs'
import { methodDocumentation } from './sdk/documentation.mjs'

const root = new URL('../', import.meta.url)
const spec = await readSpecification(
  JSON.parse(await readFile(new URL('openapi/source.json', root), 'utf8')),
)
const resources = JSON.parse(
  await readFile(new URL('scripts/sdk/resources.json', root), 'utf8'),
)
const banner = '// Generated by pnpm generate:sdk. Do not edit directly.\n'
const outputs = new Map()
const operations = new Map()
for (const [path, item] of Object.entries(spec.paths))
  for (const [method, operation] of Object.entries(item)) {
    if (!operation.operationId) continue
    assert(
      !operations.has(operation.operationId),
      `Duplicate operation: ${operation.operationId}`,
    )
    operations.set(operation.operationId, { ...operation, path, method })
  }
const enumSources = ['src/enums.ts', 'src/types/webhook.ts']
const enumBindings = JSON.parse(
  await readFile(new URL('scripts/sdk/enums.json', root), 'utf8'),
)
const enums = []
for (const filename of enumSources) {
  const source = ts.createSourceFile(
    filename,
    await readFile(new URL(filename, root), 'utf8'),
    ts.ScriptTarget.Latest,
    true,
  )
  for (const node of source.statements.filter(ts.isEnumDeclaration)) {
    const values = node.members.map((member) =>
      member.initializer && ts.isStringLiteralLike(member.initializer)
        ? member.initializer.text
        : null,
    )
    if (values.every((value) => value !== null))
      enums.push({
        name: node.name.text,
        values,
        filename: filename.replace('src/', '../').replace('.ts', ''),
      })
  }
}
for (const [pointer, name] of Object.entries(enumBindings)) {
  const schema = pointer
    .slice(2)
    .split('/')
    .reduce((value, key) => value?.[key], spec)
  const enumeration = enums.find((enumeration) => enumeration.name === name)
  assert(
    schema?.enum &&
      enumeration &&
      schema.enum.length === enumeration.values.length &&
      enumeration.values.every((value) => schema.enum.includes(value)),
    `Public enum drift at ${pointer}. Update its named SDK enum.`,
  )
  // A generation-only annotation keeps semantic aliases independent of the
  // transform hook's traversal path (which can omit properties/items/allOf).
  schema['x-sdk-enum'] = name
}
for (const mode of ['input', 'output']) {
  const imports = new Map()
  const directionalSpec = structuredClone(spec)
  function omitReadOnly(value) {
    if (!value || typeof value !== 'object') return
    for (const [key, property] of Object.entries(value.properties || {})) {
      if (property.readOnly) {
        delete value.properties[key]
        if (value.required)
          value.required = value.required.filter((name) => name !== key)
      }
    }
    for (const child of Object.values(value)) omitReadOnly(child)
  }
  if (mode === 'input') omitReadOnly(directionalSpec)
  const ast = await openapiTS(directionalSpec, {
    defaultNonNullable: false,
    emptyObjectsUnknown: true,
    transform(schema) {
      if (schema.format === 'date-time') {
        const types = [ts.factory.createTypeReferenceNode('Date')]
        if (mode === 'input')
          types.push(
            ts.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          )
        if (Array.isArray(schema.type) && schema.type.includes('null'))
          types.push(ts.factory.createLiteralTypeNode(ts.factory.createNull()))
        return types.length === 1
          ? types[0]
          : ts.factory.createUnionTypeNode(types)
      }
      if (schema.format === 'binary') {
        imports.set(
          mode === 'input' ? 'BinaryInput' : 'BinaryDownload',
          '../types/runtime',
        )
        return ts.factory.createTypeReferenceNode(
          mode === 'input' ? 'BinaryInput' : 'BinaryDownload',
        )
      }
      if (mode === 'output' && schema['x-sdk-enum']) {
        const match = enums.find(
          (enumeration) => enumeration.name === schema['x-sdk-enum'],
        )
        if (match) {
          imports.set(match.name, match.filename)
          const types = [ts.factory.createTypeReferenceNode(match.name)]
          if (Array.isArray(schema.type) && schema.type.includes('null'))
            types.push(
              ts.factory.createLiteralTypeNode(ts.factory.createNull()),
            )
          return types.length === 1
            ? types[0]
            : ts.factory.createUnionTypeNode(types)
        }
      }
    },
  })
  outputs.set(
    `src/generated/${mode}.ts`,
    banner +
      [...imports]
        .map(([name, file]) => `import type { ${name} } from '${file}';`)
        .join('\n') +
      '\n' +
      // Use prose for descriptions rather than repeated tags in union completions.
      astToString(ast).replace(/^(\s*\/\*\*|\s*\*) @description /gm, '$1 '),
  )
}
outputs.set(
  'src/generated/contracts.ts',
  banner +
    `
import type { operations as Input } from './input';
import type { operations as Output } from './output';
export type OperationId = keyof Input;
type Content<T> = T extends { content: infer C } ? C[keyof C] : never;
export type OperationBody<K extends OperationId> = Content<NonNullable<Input[K]['requestBody']>>;
export type OperationQuery<K extends OperationId> = NonNullable<Input[K]['parameters']['query']>;
export type OperationPath<K extends OperationId> = NonNullable<Input[K]['parameters']['path']>;
export type OperationResponse<K extends OperationId> = {
  [S in keyof Output[K]['responses']]: S extends number
    ? \`\${S}\` extends \`2\${string}\` ? Content<Output[K]['responses'][S]> : never
    : never;
}[keyof Output[K]['responses']];
`,
)
const used = new Set(['validateWebhookSignature'])
for (const [name, resource] of Object.entries(resources)) {
  const imports = [
    `import type { WrapperClient } from '../wrapper';`,
    `import type { OperationBody, OperationQuery, OperationResponse } from '../generated/contracts';`,
    `import { operationDatePlans } from '../generated/dates';`,
  ]
  const methods = []
  for (const [methodName, binding] of Object.entries(resource.methods)) {
    if (binding.extension === 'validateSignature') {
      imports.push(
        `import type { ApiEvent, ApiEventPayload, ApiEventType } from '../types';`,
        `import { validateSignature } from '../runtime/webhooks';`,
      )
      methods.push(
        `/**
 * Valida la firma del webhook y devuelve el evento con sus fechas como Date.
 * Usa criptografía local cuando está disponible; en otros entornos consulta la API.
 * @param data - Datos para verificar el evento.
 * @param data.secret - Secreto del webhook.
 * @param data.signature - Firma recibida en el encabezado Facturapi-Signature.
 * @param data.payload - Preferentemente, el cuerpo original como texto o bytes. También acepta un evento como objeto.
 * @returns Evento validado, siempre como objeto.
 * @throws Si la firma es inválida o el payload no se puede interpretar como JSON.
 */
validateSignature<T extends ApiEventType = any>(data: { secret: string; signature: string; payload: string | Uint8Array | ArrayBuffer | ApiEventPayload<T> }): Promise<ApiEvent<T>> { return validateSignature(this.client, data); }`,
      )
      continue
    }
    const operationId =
      typeof binding === 'string' ? binding : binding.operation
    const operation = operations.get(operationId)
    assert(
      operation,
      `Missing operation for ${name}.${methodName}: ${operationId}`,
    )
    const entry = {
      ...resolveOperationBinding(
        spec,
        operation,
        typeof binding === 'string' ? {} : binding,
      ),
      name: methodName,
      operation: operationId,
    }
    used.add(entry.operation)
    if (entry.querySchema) {
      assert(
        spec.components.schemas[entry.querySchema],
        'Missing query schema.',
      )
      assert(entry.hasQuery, 'A query schema requires query parameters.')
      imports.push(
        `import type { components as InputComponents } from '../generated/input';`,
      )
    }
    const argumentsList = entry.arguments.map((argument) => {
      let type = argument.type
      const source =
        entry.body?.argument === argument.name
          ? 'body'
          : entry.params?.argument === argument.name
            ? 'params'
            : null
      if (source)
        type =
          source === 'body' && operation.requestBody
            ? `OperationBody<'${entry.operation}'>`
            : source === 'params' && entry.hasQuery
              ? `OperationQuery<'${entry.operation}'>${argument.nullable ? ' | null' : ''}`
              : 'Record<string, unknown> | null'
      if (source === 'params' && entry.querySchema)
        type = `InputComponents['schemas']['${entry.querySchema}']${argument.nullable ? ' | null' : ''}`
      for (const [property, binding] of Object.entries(entry.body || {}))
        if (binding?.argument === argument.name)
          type = `OperationBody<'${entry.operation}'>[${JSON.stringify(property)}]`
      for (const [property, binding] of Object.entries(entry.params || {}))
        if (binding?.argument === argument.name)
          type = `OperationQuery<'${entry.operation}'>[${JSON.stringify(property)}]`
      if (entry.extension) type = argument.type
      return `${argument.name}${argument.optional ? '?' : ''}: ${type}`
    })
    const path = operation.path.replace(/\{([^}]+)\}/g, (_, key) => {
      assert(
        entry.path[key],
        `Missing path binding: ${name}.${entry.name}.${key}`,
      )
      return entry.path[key].argument
        ? `\${encodeURIComponent(${entry.path[key].argument})}`
        : entry.path[key].value
    })
    let setup = ''
    if (entry.extension === 'uploadLogo') {
      imports.push(
        `import type { BinaryInput } from '../types/runtime';`,
        `import { prepareFile } from '../runtime/uploads';`,
      )
      setup = `const formData = new FormData(); formData.append('file', await prepareFile(file, 'application/octet-stream'), 'file');`
    } else if (entry.extension === 'uploadCertificate') {
      setup = `const formData = new FormData(); const [cer, key] = await Promise.all([prepareFile(cerFile, 'application/octet-stream'), prepareFile(keyFile, 'application/octet-stream')]); formData.append('cer', cer, 'cer.cer'); formData.append('key', key, 'key.key'); formData.append('password', password);`
    }
    if (entry.extension)
      setup =
        `if (typeof FormData === 'undefined') throw new Error('FormData is not available in this runtime. Use Node.js 18+ or provide a FormData implementation.');\n` +
        setup
    const options = [
      `method: '${operation.method.toUpperCase()}'`,
      `datePlan: operationDatePlans.${entry.operation}`,
    ]
    for (const kind of ['body', 'params'])
      if (entry[kind])
        options.push(
          `${kind}: ${
            entry[kind].argument ||
            '{' +
              Object.entries(entry[kind])
                .map(
                  ([property, binding]) => `${property}: ${binding.argument}`,
                )
                .join(', ') +
              '}'
          }`,
        )
    if (entry.formData) options.push('formData')
    const pathArguments = Object.values(entry.path)
      .filter((binding) => binding.argument)
      .map((binding) => binding.argument)
    const guard = pathArguments
      .map(
        (argument) =>
          `if (!${argument}) return Promise.reject(new Error('${argument} is required'));`,
      )
      .join('\n')
    const documentation = methodDocumentation(spec, operation, entry)
    if (entry.bodyByQueryFlag) {
      assert(
        spec.components.schemas[entry.bodyByQueryFlag.true],
        'Missing conditional body schema.',
      )
      assert(
        entry.body?.argument && entry.params?.argument,
        'Conditional bodies require body and query arguments.',
      )
      imports.push(
        `import type { components as InputComponents } from '../generated/input';`,
      )
      methods.push(
        `${documentation}${entry.name}(${entry.body.argument}: InputComponents['schemas']['${entry.bodyByQueryFlag.true}'], ${entry.params.argument}: OperationQuery<'${entry.operation}'> & { ${entry.bodyByQueryFlag.property}: true }): Promise<OperationResponse<'${entry.operation}'>>;`,
      )
      methods.push(
        `${documentation}${entry.name}(${argumentsList.join(', ')}): Promise<OperationResponse<'${entry.operation}'>>;`,
      )
      argumentsList[
        entry.arguments.findIndex(
          (argument) => argument.name === entry.body.argument,
        )
      ] =
        `${entry.body.argument}: OperationBody<'${entry.operation}'> | InputComponents['schemas']['${entry.bodyByQueryFlag.true}']`
    }
    if (entry.responseByFlag) {
      imports.push(
        `import type { components as OutputComponents } from '../generated/output';`,
      )
      assert.equal(
        entry.arguments.length,
        1,
        'Response flags currently require one body argument.',
      )
      for (const flag of ['true', 'false']) {
        assert(
          spec.components.schemas[entry.responseByFlag[flag]],
          'Missing response variant schema.',
        )
        methods.push(
          `${documentation}${entry.name}(${entry.responseByFlag.argument}: OperationBody<'${entry.operation}'> & { ${entry.responseByFlag.property}${flag === 'false' ? '?' : ''}: ${flag} }): Promise<OutputComponents['schemas']['${entry.responseByFlag[flag]}']>;`,
        )
      }
      methods.push(
        `${documentation}${entry.name}(${argumentsList.join(', ')}): Promise<OperationResponse<'${entry.operation}'>>;`,
      )
    }
    methods.push(
      `${documentation}${entry.extension ? 'async ' : ''}${entry.name}(${argumentsList.join(', ')}): Promise<OperationResponse<'${entry.operation}'>> { ${guard}\n${setup}\nreturn this.client.request<OperationResponse<'${entry.operation}'>>(\`${path}\`, {${options.join(', ')}}); }`,
    )
  }
  outputs.set(
    `src/${resource.directory}/${name}.ts`,
    banner +
      [...new Set(imports)].join('\n') +
      `\nexport default class ${resource.className} {\nconstructor(public client: WrapperClient) {}\n${methods.join('\n\n')}\n}\n`,
  )
}
const models = JSON.parse(
  await readFile(new URL('scripts/sdk/models.json', root), 'utf8'),
)
const aliases = new Set([
  'ApiEvent',
  'ApiEventData',
  'Webhook',
  'SearchResult',
  ...enums.map((enumeration) => enumeration.name),
])
for (const [file, names] of Object.entries(models)) {
  let content =
    banner +
    "import type { components as InputComponents } from '../generated/input';\nimport type { components as OutputComponents } from '../generated/output';\nimport type { OperationBody, OperationQuery, OperationResponse } from '../generated/contracts';\ntype Input = InputComponents['schemas'];\ntype Output = OutputComponents['schemas'];\n"
  for (const [name, expression] of Object.entries(names)) {
    aliases.add(name)
    content += `export type ${name} = ${expression};\n`
  }
  if (file === 'common')
    content += `export * from './runtime';
export type SearchResult<T> = Output['SearchResult'] & { data: T[] };
export type PageSearchParams = ({ pagination?: 'page' } | { page: number }) & Record<string, unknown>;
export type CursorSearchParams = ({ pagination: 'cursor' } | { after: string } | { before: string }) & Record<string, unknown>;
`
  outputs.set(`src/types/${file}.ts`, content)
}
outputs.set(
  'src/generated/models.ts',
  banner +
    "import type { components as Input } from './input';\nimport type { components as Output } from './output';\n" +
    Object.keys(spec.components.schemas)
      .filter((name) => !aliases.has(name))
      .map(
        (name) =>
          `export type ${name} = ${name.endsWith('Input') ? 'Input' : 'Output'}['schemas'][${JSON.stringify(name)}];`,
      )
      .join('\n') +
    '\n',
)
const missing = [...operations.keys()].filter((name) => !used.has(name))
assert.equal(
  missing.length,
  0,
  `Unmapped public operations: ${missing.join(', ')}`,
)
// TypeScript resolves all schema references and unions for the Date compiler.
await mkdir(new URL('src/generated/', root), { recursive: true })
const plans = compileDatePlans(
  fileURLToPath(new URL('src/generated/output.ts', root)),
  outputs.get('src/generated/output.ts'),
)
outputs.set(
  'src/generated/dates.ts',
  banner +
    `import type { DatePlan } from '../runtime/dates';\nexport const datePlans: DatePlan[] = ${JSON.stringify(plans.nodes)};\nexport const componentDatePlans = ${JSON.stringify(plans.components)} as const;\nexport const operationDatePlans = ${JSON.stringify(plans.operations)} as const;\n`,
)
for (const [filename, content] of outputs) {
  const formatted = await prettier.format(content, {
    ...(await prettier.resolveConfig(fileURLToPath(new URL(filename, root)))),
    filepath: filename,
  })
  if (process.argv.includes('--check')) {
    assert(
      (await readFile(new URL(filename, root), 'utf8')) === formatted,
      `${filename} is stale. Run pnpm generate:sdk.`,
    )
  } else {
    await writeFile(new URL(filename, root), formatted)
  }
}
console.log(
  `${process.argv.includes('--check') ? 'Verified' : 'Generated'} ${operations.size} operations and ${Object.keys(spec.components.schemas).length} schemas`,
)
