// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class CartaPorteCatalogs {
  constructor(public client: WrapperClient) {}
  /**
   * Buscar códigos de transporte aéreo
   *
   * Devuelve entradas del catálogo de aerolíneas que coinciden con la consulta. Usado para el complemento Carta Porte.
   *
   */
  searchAirTransportCodes(
    params: OperationQuery<'searchCartaPorteAirTransportCodes'> | null,
  ): Promise<OperationResponse<'searchCartaPorteAirTransportCodes'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteAirTransportCodes'>
    >(`/catalogs/cartaporte/3.1/air-transport-codes`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteAirTransportCodes,
      params: params,
    })
  }

  /**
   * Buscar configuraciones de autotransporte
   *
   * Devuelve configuraciones de transporte (p. ej., camión/semirremolque).
   */
  searchTransportConfigs(
    params: OperationQuery<'searchCartaPorteTransportConfigs'> | null,
  ): Promise<OperationResponse<'searchCartaPorteTransportConfigs'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteTransportConfigs'>
    >(`/catalogs/cartaporte/3.1/transport-configs`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteTransportConfigs,
      params: params,
    })
  }

  /**
   * Buscar derechos de paso
   *
   * Devuelve derechos de paso ferroviarios que coinciden con la consulta.
   */
  searchRightsOfPassage(
    params: OperationQuery<'searchCartaPorteRightsOfPassage'> | null,
  ): Promise<OperationResponse<'searchCartaPorteRightsOfPassage'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteRightsOfPassage'>
    >(`/catalogs/cartaporte/3.1/rights-of-passage`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteRightsOfPassage,
      params: params,
    })
  }

  /**
   * Buscar documentos aduaneros
   *
   * Devuelve tipos de documentos aduaneros.
   */
  searchCustomsDocuments(
    params: OperationQuery<'searchCartaPorteCustomsDocuments'> | null,
  ): Promise<OperationResponse<'searchCartaPorteCustomsDocuments'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteCustomsDocuments'>
    >(`/catalogs/cartaporte/3.1/customs-documents`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteCustomsDocuments,
      params: params,
    })
  }

  /**
   * Buscar tipos de empaque
   *
   * Devuelve tipos de empaque para mercancías.
   */
  searchPackagingTypes(
    params: OperationQuery<'searchCartaPortePackagingTypes'> | null,
  ): Promise<OperationResponse<'searchCartaPortePackagingTypes'>> {
    return this.client.request<
      OperationResponse<'searchCartaPortePackagingTypes'>
    >(`/catalogs/cartaporte/3.1/packaging-types`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPortePackagingTypes,
      params: params,
    })
  }

  /**
   * Buscar tipos de remolque
   *
   * Devuelve tipos de remolque/semirremolque.
   */
  searchTrailerTypes(
    params: OperationQuery<'searchCartaPorteTrailerTypes'> | null,
  ): Promise<OperationResponse<'searchCartaPorteTrailerTypes'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteTrailerTypes'>
    >(`/catalogs/cartaporte/3.1/trailer-types`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteTrailerTypes,
      params: params,
    })
  }

  /**
   * Buscar materiales peligrosos
   *
   * Devuelve entradas del catálogo de materiales peligrosos.
   */
  searchHazardousMaterials(
    params: OperationQuery<'searchCartaPorteHazardousMaterials'> | null,
  ): Promise<OperationResponse<'searchCartaPorteHazardousMaterials'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteHazardousMaterials'>
    >(`/catalogs/cartaporte/3.1/hazardous-materials`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteHazardousMaterials,
      params: params,
    })
  }

  /**
   * Buscar autorizaciones navales
   *
   * Devuelve códigos de autorización naval (solo `key`).
   */
  searchNavalAuthorizations(
    params: OperationQuery<'searchCartaPorteNavalAuthorizations'> | null,
  ): Promise<OperationResponse<'searchCartaPorteNavalAuthorizations'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteNavalAuthorizations'>
    >(`/catalogs/cartaporte/3.1/naval-authorizations`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteNavalAuthorizations,
      params: params,
    })
  }

  /**
   * Buscar estaciones/puertos
   *
   * Devuelve entradas de estaciones aéreas/marítimas/terrestres.
   */
  searchPortStations(
    params: OperationQuery<'searchCartaPortePortStations'> | null,
  ): Promise<OperationResponse<'searchCartaPortePortStations'>> {
    return this.client.request<
      OperationResponse<'searchCartaPortePortStations'>
    >(`/catalogs/cartaporte/3.1/port-stations`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPortePortStations,
      params: params,
    })
  }

  /**
   * Buscar contenedores marítimos
   *
   * Devuelve tipos de contenedores marítimos.
   */
  searchMarineContainers(
    params: OperationQuery<'searchCartaPorteMarineContainers'> | null,
  ): Promise<OperationResponse<'searchCartaPorteMarineContainers'>> {
    return this.client.request<
      OperationResponse<'searchCartaPorteMarineContainers'>
    >(`/catalogs/cartaporte/3.1/marine-containers`, {
      method: 'GET',
      datePlan: operationDatePlans.searchCartaPorteMarineContainers,
      params: params,
    })
  }
}
