// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Catalogs {
  constructor(public client: WrapperClient) {}
  /**
   * Clave Producto/Servicio
   *
   * Busca en el catálogo Productos/Servicios del SAT, el cual contiene la clave a incluir en la factura.
   */
  searchProducts(
    params: OperationQuery<'searchProducts'> | null,
  ): Promise<OperationResponse<'searchProducts'>> {
    return this.client.request<OperationResponse<'searchProducts'>>(
      `/catalogs/products`,
      {
        method: 'GET',
        datePlan: operationDatePlans.searchProducts,
        params: params,
      },
    )
  }

  /**
   * Unidades de medida
   *
   * Busca en el catálogo de Unidades de Medida del SAT.
   */
  searchUnits(
    params: OperationQuery<'searchUnits'> | null,
  ): Promise<OperationResponse<'searchUnits'>> {
    return this.client.request<OperationResponse<'searchUnits'>>(
      `/catalogs/units`,
      {
        method: 'GET',
        datePlan: operationDatePlans.searchUnits,
        params: params,
      },
    )
  }
}
