// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class ComercioExteriorCatalogs {
  constructor(public client: WrapperClient) {}
  /**
   * Buscar fracciones arancelarias
   *
   * Devuelve fracciones arancelarias que coinciden con la consulta.
   */
  searchTariffFractions(
    params: OperationQuery<'searchComercioExteriorTariffFractions'>,
  ): Promise<OperationResponse<'searchComercioExteriorTariffFractions'>> {
    return this.client.request<
      OperationResponse<'searchComercioExteriorTariffFractions'>
    >(`/catalogs/comercioexterior/2.0/tariff-fractions`, {
      method: 'GET',
      datePlan: operationDatePlans.searchComercioExteriorTariffFractions,
      params: params,
    })
  }
}
