// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
export default class Tools {
  constructor(public client: WrapperClient) {}
  /**
   * Validar RFC
   *
   * Consulta el estado de un RFC en la lista de **EFOS** (Empresas que
   * Facturan Operaciones Simuladas). Al aparecer en esta lista, el RFC es o
   * fue sospechoso de incurrir en simulación de operaciones fiscales
   * (empresas factureras).
   *
   * La respuesta (detallada más abajo) incluye los resultados de esta
   * validación. Se incluye la propiedad
   * booleana `is_valid`, que Facturapi resuelve interpretando la respuesta.
   * Un valor de `true` para esta propiedad indica que el RFC no tiene asuntos
   * por resolver y está libre de problemas; y lo contrario para `false`.
   *
   * Adicionalmente puedes consultar la propiedad data para ver los valores
   * en bruto de la consulta al SAT.
   *
   * @param taxId - taxId
   * @returns Resultado de la validación
   */
  validateTaxId(
    taxId: OperationQuery<'validateTaxId'>['tax_id'],
  ): Promise<OperationResponse<'validateTaxId'>> {
    return this.client.request<OperationResponse<'validateTaxId'>>(
      `/tools/tax_id_validation`,
      {
        method: 'GET',
        datePlan: operationDatePlans.validateTaxId,
        params: { tax_id: taxId },
      },
    )
  }

  /**
   * Health check (Pulso)
   *
   * Comprueba que la API está disponible. Este endpoint requiere una llave secreta de API.
   *
   * @returns La API está operando con normalidad.
   */
  checkApiHealth(): Promise<OperationResponse<'checkApiHealth'>> {
    return this.client.request<OperationResponse<'checkApiHealth'>>(`/check`, {
      method: 'GET',
      datePlan: operationDatePlans.checkApiHealth,
    })
  }
}
