// Generated by pnpm generate:sdk. Do not edit directly.
import type { WrapperClient } from '../wrapper'
import type {
  OperationBody,
  OperationQuery,
  OperationResponse,
} from '../generated/contracts'
import { operationDatePlans } from '../generated/dates'
import type { ApiEvent, ApiEventPayload, ApiEventType } from '../types'
import { validateSignature } from '../runtime/webhooks'
export default class Webhooks {
  constructor(public client: WrapperClient) {}
  /**
   * Crear Webhook
   *
   * Registra un nuevo webhook en tu organización de Facturapi.
   * Utiliza esta llamada para recibir notificaciones de eventos asíncronos a la API.
   * Los webhooks de ambiente test y ambiente live son independientes.
   *
   * @param data - Datos de la solicitud.
   * @returns Nuevo objeto `Webhook` creado
   */
  create(
    data: OperationBody<'createWebhook'>,
  ): Promise<OperationResponse<'createWebhook'>> {
    return this.client.request<OperationResponse<'createWebhook'>>(
      `/webhooks`,
      {
        method: 'POST',
        datePlan: operationDatePlans.createWebhook,
        body: data,
      },
    )
  }

  /**
   * Listar webhooks
   *
   * Retorna una lista de webhooks creados previamente para la organización.
   *
   * @param params - Parámetros de consulta.
   * @returns Resultado de la búsqueda
   */
  list(
    params: OperationQuery<'listWebhooks'>,
  ): Promise<OperationResponse<'listWebhooks'>> {
    return this.client.request<OperationResponse<'listWebhooks'>>(`/webhooks`, {
      method: 'GET',
      datePlan: operationDatePlans.listWebhooks,
      params: params,
    })
  }

  /**
   * Obtener webhook por ID
   *
   * Regresa el objeto "Webhook" relacionado al `id` especificado.
   *
   * @param id - ID del objeto a obtener
   * @returns Objeto `Webhook`
   */
  retrieve(id: string): Promise<OperationResponse<'getWebhook'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'getWebhook'>>(
      `/webhooks/${encodeURIComponent(id)}`,
      { method: 'GET', datePlan: operationDatePlans.getWebhook },
    )
  }

  /**
   * Editar webhook
   *
   * Actualiza la información de un Webhook existente con los parámetros que envíes en la petición.
   *
   * @param id - ID del objeto a editar
   * @param data - Datos de la solicitud.
   * @returns Objeto `Webhook` editado correctamente
   */
  update(
    id: string,
    data: OperationBody<'editWebhook'>,
  ): Promise<OperationResponse<'editWebhook'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'editWebhook'>>(
      `/webhooks/${encodeURIComponent(id)}`,
      { method: 'PUT', datePlan: operationDatePlans.editWebhook, body: data },
    )
  }

  /**
   * Eliminar Webhook
   *
   * Elimina el webhook perteneciente a la organización.
   *
   * @param id - ID del objeto a eliminar
   * @returns Objeto `Webhook` eliminado correctamente
   */
  del(id: string): Promise<OperationResponse<'deleteWebhook'>> {
    if (!id) return Promise.reject(new Error('id is required'))

    return this.client.request<OperationResponse<'deleteWebhook'>>(
      `/webhooks/${encodeURIComponent(id)}`,
      { method: 'DELETE', datePlan: operationDatePlans.deleteWebhook },
    )
  }

  /**
   * Valida la firma del webhook y devuelve el evento con sus fechas como Date.
   * Usa criptografía local cuando está disponible; en otros entornos consulta la API.
   * @param data - Datos para verificar el evento.
   * @param data.secret - Secreto del webhook.
   * @param data.signature - Firma recibida en el encabezado Facturapi-Signature.
   * @param data.payload - Preferentemente, el cuerpo original como texto o bytes. También acepta un evento como objeto.
   * @returns Evento validado, siempre como objeto.
   * @throws Si la firma es inválida o el payload no se puede interpretar como JSON.
   */
  validateSignature<T extends ApiEventType = any>(data: {
    secret: string
    signature: string
    payload: string | Uint8Array | ArrayBuffer | ApiEventPayload<T>
  }): Promise<ApiEvent<T>> {
    return validateSignature(this.client, data)
  }
}
